declare namespace App.Data {
export type ChangePasswordData = {
current_password: string;
password: string;
password_confirmation: string | null;
};
export type CustomerData = {
type: string | null;
first_name: string | null;
last_name: string | null;
company_name: string | null;
vat_number: string | null;
tax_code: string | null;
email: string | null;
phone: string | null;
mobile: string | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
country: string | null;
payment_terms: string | null;
discount_percentage: number | null;
notes: string | null;
is_active: boolean | null;
};
export type DdtData = {
id?: number;
code?: string;
type: App.Enums.DdtType;
supplier_id: number | null;
customer_id: number | null;
project_id: number | null;
price_list_id: number | null;
from_warehouse_id: number;
to_warehouse_id: number | null;
ddt_number: string;
ddt_date: string;
transport_date: string | null;
delivered_at: string | null;
carrier_name: string | null;
tracking_number: string | null;
rental_start_date: string | null;
rental_end_date: string | null;
rental_actual_return_date: string | null;
parent_ddt_id: number | null;
return_reason: App.Enums.ReturnReason | null;
return_notes: string | null;
status: App.Enums.DdtStatus | null;
notes: string | null;
created_by: number | null;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
supplier?: App.Data.SupplierData | null;
customer?: App.Data.CustomerData | null;
project?: App.Data.ProjectData | null;
price_list?: App.Data.PriceListData | null;
from_warehouse?: App.Data.WarehouseData | null;
to_warehouse?: App.Data.WarehouseData | null;
created_by_user?: App.Data.UserData | null;
parent_ddt?: App.Data.DdtData | null;
items?: Array<App.Data.DdtItemData>;
stock_movements?: Array<App.Data.StockMovementData> | null;
total_items: number;
total_quantity: number;
can_be_confirmed: boolean;
can_be_cancelled: boolean;
is_delivered: boolean;
};
export type DdtItemData = {
id?: number;
ddt_id?: number | null;
product_id: number;
quantity: number;
unit: string;
unit_cost: number | null;
notes: string | null;
kit_assembly_id: number | null;
created_at?: string;
updated_at?: string;
product?: App.Data.ProductData | null;
kit_assembly?: App.Data.KitAssemblyData | null;
total_cost: number;
};
export type DiscountFamilyData = {
id?: number;
supplier_id: number;
code: string;
name: string;
description: string | null;
discount_1: number;
discount_2: number;
discount_3: number;
is_active: boolean;
};
export type FinalBalanceData = {
project_id: number;
project_name: string;
project_code: string;
customer_name: string | null;
currency: string;
quote_total: number;
quote_labor_total: number;
quote_material_total: number;
extra_labor_revenue: number;
billable_expenses_revenue: number;
total_revenue: number;
labor_cost_total: number;
external_labor_cost: number;
internal_labor_cost: number;
material_cost_total: number;
approved_expenses_total: number;
total_cost: number;
gross_margin: number;
gross_margin_percent: number;
workers: Array<App.Data.ProjectWorkerData> | null;
expenses: Array<App.Data.ProjectExpenseData> | null;
generated_at: string | null;
};
export type FinancialResourceData = {
id?: number;
type: App.Enums.FinancialResourceType;
name: string;
description: string | null;
details: Array<any> | null;
is_active: boolean;
is_default: boolean;
sort_order: number;
notes: string | null;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
display_name?: string;
formatted_bank_info?: string;
formatted_cash_info?: string;
formatted_card_info?: string;
};
export type ForgotPasswordData = {
email: string;
};
export type InventoryData = {
id?: number;
product_id: number;
warehouse_id: number;
quantity_available: number | null;
quantity_reserved: number | null;
quantity_in_transit: number | null;
quantity_quarantine: number | null;
minimum_stock: number | null;
maximum_stock: number | null;
last_count_date: string | null;
created_at?: string;
updated_at?: string;
product?: App.Data.ProductData | null;
warehouse?: App.Data.WarehouseData | null;
quantity_free: number;
is_low_stock: boolean;
stock_value: number;
};
export type KitAssemblyData = {
id?: number;
product_id: number;
name: string;
status: App.Enums.KitAssemblyStatus;
warehouse_id: number | null;
location: string | null;
notes: string | null;
assembled_at: string | null;
disassembled_at: string | null;
assembled_by_user_id: number | null;
disassembled_by_user_id: number | null;
created_at?: string;
updated_at?: string;
product?: App.Data.ProductData | null;
warehouse?: App.Data.WarehouseData | null;
items?: Array<App.Data.KitAssemblyItemData> | null;
};
export type KitAssemblyItemData = {
id?: number;
kit_assembly_id: number;
product_id: number;
quantity: number;
serial_number: string | null;
notes: string | null;
created_at?: string;
updated_at?: string;
product?: App.Data.ProductData | null;
};
export type PaymentTermData = {
id?: number;
code: string;
name: string;
description: string | null;
days: number;
payment_type: string;
is_default: boolean;
is_active: boolean;
sort_order: number;
};
export type PermissionData = {
name: string;
display_name?: string;
description?: string | null;
guard_name: string;
id?: number;
module?: string;
action?: string;
created_at?: string;
updated_at?: string;
};
export type PriceListData = {
id: number | null;
name: string;
code: string;
description: string | null;
calculation_mode: App.Enums.PriceListCalculationMode;
adjustment_type: App.Enums.PriceListAdjustmentType;
adjustment_value: number | null;
applies_to: App.Enums.PriceListAppliesTo;
category_id: number | null;
department_filter: string | null;
valid_from: string | null;
valid_to: string | null;
is_active: boolean;
is_default: boolean;
priority: number;
category?: App.Data.ProductCategoryData | null;
items?: Array<App.Data.PriceListItemData> | null;
items_count: number | null;
};
export type PriceListItemData = {
id: number | null;
price_list_id: number;
product_id: number;
sale_price: number;
is_manual_price: boolean | null;
rental_daily: number | null;
rental_hourly: number | null;
rental_half_day: number | null;
rental_weekly: number | null;
rental_monthly: number | null;
rental_seasonal: number | null;
is_manual_rental: boolean | null;
is_active: boolean | null;
notes: string | null;
priceList?: App.Data.PriceListData | null;
product?: App.Data.ProductData | null;
final_sale_price: number | null;
final_rental_daily: number | null;
final_rental_hourly: number | null;
final_rental_half_day: number | null;
final_rental_weekly: number | null;
final_rental_monthly: number | null;
final_rental_seasonal: number | null;
};
export type ProductBrandData = {
id?: number;
name: string;
code?: string;
description: string | null;
logo_url: string | null;
website: string | null;
is_active?: boolean;
};
export type ProductCategoryData = {
id: number | null;
code: string;
name: string;
description: string | null;
icon: string | null;
color: string | null;
sort_order?: number;
is_active?: boolean;
rental_profile_id: number | null;
rentalProfile: App.Data.RentalProfileData | null;
};
export type ProductComponentData = {
id?: number;
kit_product_id: number;
component_product_id: number;
quantity: number;
notes?: string | null;
created_at?: string;
updated_at?: string;
};
export type ProductData = {
id?: number;
code: string;
internal_code: string | null;
ean: string | null;
etim_code: string | null;
name: string;
description: string | null;
category_id: number | null;
brand_id: number | null;
product_type: App.Enums.ProductType;
kit_type: App.Enums.KitType | null;
is_package?: boolean;
package_weight: number | null;
package_volume: number | null;
package_dimensions: string | null;
is_rentable?: boolean;
ownership_type?: string;
is_premium?: boolean;
subrental_markup: number | null;
rental_price_estimated?: boolean;
estimated_base_day: number | null;
quantity_out_on_rental?: number;
unit: string | null;
standard_cost: number | null;
manufacturer_cost_price: number | null;
manufacturer_retail_price: number | null;
sale_markup_percent: number | null;
barcode: string | null;
qr_code: string | null;
default_supplier_id: number | null;
reorder_level: number | null;
reorder_quantity: number | null;
lead_time_days: number | null;
location: string | null;
notes: string | null;
is_active: boolean | null;
is_labor_role: boolean;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
category?: App.Data.ProductCategoryData | null;
brand?: App.Data.ProductBrandData | null;
defaultSupplier?: App.Data.SupplierData | null;
relations?: Array<App.Data.ProductRelationData> | null;
media?: Array<App.Data.ProductMediaData> | null;
priceListItems?: Array<App.Data.PriceListItemData> | null;
composite_total_cost?: number;
total_stock?: number;
available_stock?: number;
};
export type ProductMediaData = {
id?: number;
collection_name: string;
file_name?: string;
mime_type?: string;
size?: number;
url?: string;
thumb_url?: string | null;
medium_url?: string | null;
description: string | null;
is_primary?: boolean;
use_in_quotes?: boolean;
use_in_projects?: boolean;
document_type: string | null;
valid_until: string | null;
sort_order?: number;
created_at?: string;
is_pdf_conversion?: boolean;
pdf_media_id: number | null;
pdf_url: string | null;
};
export type ProductRelationData = {
id: number | null;
product_id: number;
related_product_id: number;
relation_type_id: number;
quantity_type: App.Enums.ProductRelationQuantityType;
quantity_value: string;
is_visible_in_quote: boolean;
is_visible_in_material_list: boolean;
is_required_for_stock: boolean;
is_optional: boolean;
min_quantity_trigger: number | null;
max_quantity_trigger: number | null;
sort_order: number | null;
notes: string | null;
relatedProduct?: App.Data.ProductData | null;
relationType?: App.Data.ProductRelationTypeData | null;
};
export type ProductRelationTypeData = {
id: number | null;
code: string;
name: string;
description: string | null;
icon: string | null;
color: string | null;
sort_order: number;
is_active: boolean;
};
export type ProductSubrentalSupplierData = {
id?: number;
product_id: number;
supplier_id: number;
day_rate: number;
reliability_score: number;
is_preferred: boolean;
last_updated: string | null;
notes: string | null;
created_at?: string;
updated_at?: string;
product?: App.Data.ProductData | null;
supplier?: App.Data.SupplierData | null;
};
export type ProductUnitTypeData = {
id: number | null;
code: string;
name_it: string;
symbol_it: string;
name_en: string;
symbol_en: string;
aliases: Array<any> | null;
category: string | null;
conversion_factor: number | null;
is_active: boolean | null;
sort_order: number | null;
};
export type ProjectData = {
id: number | null;
code: string | null;
name: string;
description: string | null;
customer_id: number;
quote_id: number | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
country: string | null;
latitude: number | null;
longitude: number | null;
gps_radius: number | null;
project_manager_id: number | null;
estimated_amount: number | null;
actual_cost: number | null;
invoiced_amount: number | null;
start_date: string | null;
estimated_end_date: string | null;
actual_end_date: string | null;
status: string;
priority: string | null;
notes: string | null;
internal_notes: string | null;
is_active: boolean;
};
export type ProjectExpenseData = {
id: number | null;
project_id: number;
project_worker_id: number | null;
submitted_by_user_id: number | null;
category: App.Enums.ProjectExpenseCategory;
description: string;
amount: number;
expense_date: string;
is_billable_to_client: boolean;
receipt_media_id: number | null;
status: App.Enums.ProjectExpenseStatus;
approved_by_user_id: number | null;
approved_at: string | null;
rejection_reason: string | null;
notes: string | null;
submitted_by_name: string | null;
category_label: string | null;
};
export type ProjectLaborCostData = {
id: number | null;
project_id: number | null;
cost_type: string | null;
worker_id: number | null;
contractor_id: number | null;
description: string | null;
work_date: string | null;
hours_worked: number | null;
quantity: number | null;
unit_rate: number | null;
total_cost: number | null;
currency: string | null;
is_overtime: boolean;
is_holiday: boolean;
cost_category: string | null;
invoice_number: string | null;
invoice_date: string | null;
is_invoiced: boolean;
notes: string | null;
};
export type ProjectLaborLogData = {
id: number | null;
project_id: number;
project_worker_id: number;
worker_id: number | null;
schedule_day_id: number | null;
log_date: string;
regular_hours: number;
overtime_hours: number;
description: string | null;
submitted_by_user_id: number | null;
status: App.Enums.ProjectLogStatus;
approved_by_user_id: number | null;
approved_at: string | null;
rejection_reason: string | null;
labor_cost_id: number | null;
total_hours: number | null;
submitted_by_name: string | null;
};
export type ProjectMaterialData = {
id: number | null;
project_id: number | null;
product_id: number | null;
quote_item_id: number | null;
is_extra: boolean | null;
requested_by: number | null;
requested_at: string | null;
extra_reason: string | null;
planned_quantity: number | null;
allocated_quantity: number | null;
delivered_quantity: number | null;
used_quantity: number | null;
returned_quantity: number | null;
planned_unit_cost: number | null;
actual_unit_cost: number | null;
status: App.Enums.ProjectMaterialStatus | null;
required_date: string | null;
delivery_date: string | null;
notes: string | null;
kit_assembly_id: number | null;
remaining_quantity: number | null;
usage_percentage: number | null;
planned_total_cost: number | null;
actual_total_cost: number | null;
cost_variance: number | null;
product_name: string | null;
product_code: string | null;
product?: App.Data.ProductData | null;
quoteItem?: App.Data.QuoteItemData | null;
kit_assembly?: App.Data.KitAssemblyData | null;
};
export type ProjectRoleData = {
id: number | null;
name: string;
slug: string | null;
description: string | null;
color: string | null;
sort_order: number | null;
is_active: boolean;
};
export type ProjectWorkerData = {
id: number | null;
project_id: number | null;
worker_id: number | null;
status: string | null;
assigned_by_user_id: number | null;
site_role: string | null;
assigned_from: string | null;
assigned_to: string | null;
responded_at: string | null;
response_due_at: string | null;
rejection_reason: string | null;
hourly_rate_override: number | null;
fixed_rate_override: number | null;
rate_override_notes: string | null;
estimated_hours: number | null;
is_active: boolean;
notes: string | null;
role_name: string | null;
slot_index: number;
quote_item_id: number | null;
estimated_days: number | null;
budget_cost_rate: number | null;
actual_cost_rate: number | null;
customer_rate: number | null;
is_external: boolean;
is_scheduled: boolean;
worker_name: string | null;
worker_code: string | null;
};
export type ProjectWorkerScheduleData = {
id: number | null;
project_worker_id: number;
scheduled_date: string;
planned_start_time: string | null;
planned_end_time: string | null;
planned_hours: number | null;
status: App.Enums.ProjectScheduleDayStatus;
accepted_at: string | null;
rejected_at: string | null;
rejection_reason: string | null;
notes: string | null;
effective_planned_hours: number | null;
};
export type QuoteData = {
title: string;
customer_id: number;
id?: number;
code?: string;
project_manager_id: number | null;
description: string | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
status: string;
quote_type: App.Enums.QuoteType;
event_days: number | null;
issue_date: string | null;
expiry_date: string | null;
sent_date: string | null;
approved_date: string | null;
price_list_id: number | null;
payment_term_id: number | null;
financial_resource_id: number | null;
template_id: number | null;
project_id: number | null;
warranty_type_id: number | null;
subtotal: number;
discount_percentage: number;
discount_amount: number;
tax_percentage: number;
tax_amount: number;
total_amount: number;
deposit_percentage: number | null;
deposit_amount: number | null;
work_start_description: string | null;
work_start_date: string | null;
work_duration_description: string | null;
work_end_date: string | null;
tax_included: boolean;
show_unit_prices: boolean;
show_product_codes: boolean;
show_vat: boolean;
show_section_totals: boolean;
vat_included_in_prices: boolean;
include_terms_and_conditions: boolean;
notes: string | null;
terms_and_conditions: string | null;
footer_text: string | null;
customer?: App.Data.CustomerData;
projectManager?: App.Data.UserData;
priceList?: App.Data.PriceListData;
paymentTerm?: App.Data.PaymentTermData;
financialResource?: App.Data.FinancialResourceData;
warrantyType?: App.Data.WarrantyTypeData;
project?: App.Data.ProjectData;
items?: Array<App.Data.QuoteItemData>;
full_address?: string;
};
export type QuoteItemData = {
type: App.Enums.QuoteItemType;
description: string;
id?: number;
quote_id: number | null;
parent_id: number | null;
product_id: number | null;
price_list_item_id: number | null;
code: string | null;
notes: string | null;
sort_order: number;
unit: string | null;
billing_unit: App.Enums.QuoteItemBillingUnit;
duration: number | null;
quantity: number | null;
unit_price: number | null;
cost_price: number | null;
discount_percentage: number;
subtotal: number;
discount_amount: number;
total: number;
vat_rate: number | null;
vat_amount: number;
total_with_vat: number;
hide_unit_price: boolean;
include_image: boolean;
included_media_ids: Array<number> | null;
expand_kit: boolean;
product?: App.Data.ProductData;
priceListItem?: App.Data.PriceListItemData;
parent?: App.Data.QuoteItemData;
children?: Array<App.Data.QuoteItemData>;
margin_amount: number | null;
margin_percent: number | null;
};
export type RentalProfileData = {
id?: number;
name: string;
sector: string;
exponent_curve: number;
decay_strength: number;
max_duration_reference: number;
duration_offset: number;
max_period_cap_days: number;
is_default: boolean;
is_active: boolean;
created_at: string | null;
updated_at: string | null;
};
export type ResetPasswordData = {
email: string;
password: string;
password_confirmation: string | null;
token: string;
};
export type RoleData = {
id?: number;
name: string;
display_name?: string;
description?: string | null;
guard_name: string;
permissions: Array<string>;
permissions_count?: number;
users_count?: number;
created_at?: string;
updated_at?: string;
};
export type SettingData = {
id: number | null;
key: string;
value: any;
type: string | null;
group: string | null;
user_id: number | null;
is_public: boolean;
description: string | null;
validation_rules: Array<any> | null;
allowed_values: Array<any> | null;
min_value: number | null;
max_value: number | null;
default_value: any;
order: number;
is_feature_flag: boolean;
created_at: string | null;
updated_at: string | null;
};
export type StockMovementData = {
id?: number;
code?: string;
ddt_id: number | null;
product_id: number;
warehouse_id: number;
type: App.Enums.StockMovementType;
quantity: number;
unit_cost: number | null;
movement_date: string;
from_warehouse_id: number | null;
to_warehouse_id: number | null;
project_id: number | null;
supplier_id: number | null;
supplier_document: string | null;
user_id: number | null;
notes: string | null;
reference_document: string | null;
created_at?: string;
updated_at?: string;
product?: App.Data.ProductData | null;
warehouse?: App.Data.WarehouseData | null;
from_warehouse?: App.Data.WarehouseData | null;
to_warehouse?: App.Data.WarehouseData | null;
project: any | null;
supplier?: App.Data.SupplierData | null;
user?: App.Data.UserData | null;
ddt: any | null;
total_value: number;
type_label: string;
type_color: string;
is_outgoing: boolean;
is_incoming: boolean;
};
export type SubrentalCostHistoryData = {
id?: number;
product_id: number;
supplier_id: number;
quote_id: number | null;
actual_cost: number;
duration_days: number;
margin_generated: number | null;
date: string;
created_at: string | null;
updated_at: string | null;
};
export type SupplierData = {
id?: number;
code: string;
company_name: string;
supplier_type: App.Enums.SupplierType;
personnel_type?: App.Enums.PersonnelType | null;
vat_number?: string | null;
tax_code?: string | null;
email?: string | null;
phone?: string | null;
mobile?: string | null;
website?: string | null;
address?: string | null;
city?: string | null;
province?: string | null;
postal_code?: string | null;
country?: string | null;
payment_terms?: string | null;
delivery_terms?: string | null;
discount_percentage?: number | null;
iban?: string | null;
bank_name?: string | null;
contact_person?: string | null;
contact_email?: string | null;
contact_phone?: string | null;
notes?: string | null;
specializations?: Array<any> | null;
is_active: boolean;
created_at?: string;
updated_at?: string;
deleted_at?: string | null;
};
export type SupplierProductData = {
id: number | null;
supplier_id: number;
product_id: number;
supplier_product_code: string | null;
supplier_ean: string | null;
purchase_price: number;
wholesale_price: number | null;
retail_price: number | null;
discount_family_id: number | null;
manual_discount_1: number | null;
manual_discount_2: number | null;
manual_discount_3: number | null;
package_quantity: number | null;
minimum_order_quantity: number | null;
maximum_order_quantity: number | null;
multiple_order_quantity: number | null;
lead_time_days: number | null;
payment_term_id: number | null;
price_multiplier: number | null;
currency: string | null;
last_price_update: string | null;
is_preferred_supplier: boolean | null;
is_active: boolean | null;
notes: string | null;
supplier?: App.Data.SupplierData | null;
product?: App.Data.ProductData | null;
discountFamily?: App.Data.DiscountFamilyData | null;
paymentTerm?: App.Data.PaymentTermData | null;
final_price: number | null;
effective_discounts: Array<any> | null;
created_at: string | null;
updated_at: string | null;
};
export type UserData = {
name: string;
email: string;
is_active: boolean;
roles: Array<string>;
id?: number;
password?: string | null;
password_confirmation?: string | null;
permissions?: Array<any>;
worker: any;
created_at?: string;
updated_at?: string;
};
export type WarehouseData = {
id: number | null;
code: string;
name: string;
type: App.Enums.WarehouseType;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
manager_id: number | null;
notes: string | null;
is_active: boolean;
full_address: string | null;
total_value: number | null;
manager?: App.Data.UserData | null;
};
export type WarrantyTypeData = {
id?: number;
name: string;
years: number | null;
description: string | null;
exclusions: Array<string> | null;
is_default: boolean;
is_active: boolean;
sort_order: number;
};
}
declare namespace App.Data.Landlord {
export type GlobalUserData = {
id?: string;
name: string;
email: string;
phone: string | null;
tax_code: string | null;
fiscal_code: string | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
country: string | null;
iban: string | null;
is_landlord_admin: boolean | null;
created_at?: string;
};
export type PlanData = {
id?: number;
name: string;
slug: string;
description: string | null;
price: number | null;
price_yearly: number | null;
is_active: boolean;
sort_order: number;
trial_days: number;
features?: Array<App.Data.Landlord.PlanFeatureData> | null;
};
export type PlanFeatureData = {
id?: number;
plan_id?: number;
feature_key: string;
price: number | null;
price_yearly: number | null;
limits: Array<any> | null;
};
export type TenantData = {
id?: string;
name: string;
slug: string | null;
created_at?: string;
subscription?: App.Data.Landlord.TenantSubscriptionData | null;
};
export type TenantMembershipData = {
id?: number;
global_user_id: string;
tenant_id: string;
role: string;
status: string;
created_at?: string;
};
export type TenantOverviewItemData = {
tenant_id: string;
tenant_name: string;
role: string;
worker_id: number | null;
projects_count: number;
};
export type TenantSubscriptionData = {
id?: number;
tenant_id: string;
plan_id: number | null;
status: string;
starts_at: string | null;
ends_at: string | null;
trial_ends_at: string | null;
billing_cycle: string;
renews_at: string | null;
notes: string | null;
created_at?: string;
plan?: App.Data.Landlord.PlanData | null;
addons?: Array<App.Data.Landlord.TenantSubscriptionFeatureData> | null;
total_price: number | null;
};
export type TenantSubscriptionFeatureData = {
id?: number;
feature_key: string;
price_at_purchase: number | null;
};
}
declare namespace App.Enums {
export type ContractType = 'permanent' | 'fixed_term' | 'seasonal' | 'project_based' | 'internship';
export type ContractorType = 'cooperative' | 'subcontractor' | 'temporary_agency';
export type DdtStatus = 'draft' | 'issued' | 'in_transit' | 'delivered' | 'cancelled';
export type DdtType = 'incoming' | 'outgoing' | 'internal' | 'rental_out' | 'rental_return' | 'return_from_customer' | 'return_to_supplier';
export type DependencyType = 'container' | 'accessory' | 'cable' | 'consumable' | 'tool';
export type FinancialResourceType = 'bank_account' | 'cash' | 'card';
export type KitAssemblyStatus = 'assembled' | 'in_use' | 'returned' | 'disassembled';
export type KitType = 'distributed' | 'assembled';
export type LaborCostType = 'internal_labor' | 'subcontractor' | 'contractor';
export type MaterialRequestPriority = 'low' | 'medium' | 'high' | 'urgent';
export type MaterialRequestStatus = 'pending' | 'approved' | 'rejected' | 'delivered';
export type PaymentMethod = 'bank_transfer' | 'credit_card' | 'debit_card' | 'cash' | 'check' | 'riba' | 'rid' | 'paypal' | 'sepa_dd' | 'wire_transfer';
export type PayrollFrequency = 'monthly' | 'biweekly' | 'weekly';
export type PersonnelType = 'cooperative' | 'staffing_agency' | 'rental_with_operator' | 'subcontractor' | 'technical_services';
export type PriceListAdjustmentType = 'percentage' | 'fixed' | 'none' | 'multiplier';
export type PriceListAppliesTo = 'sale' | 'rental' | 'both';
export type PriceListCalculationMode = 'automatic' | 'manual';
export type ProductRelationQuantityType = 'fixed' | 'multiplied' | 'formula';
export type ProductType = 'article' | 'service' | 'composite' | 'kit';
export type ProjectExpenseCategory = 'travel' | 'accommodation' | 'meal' | 'fuel' | 'toll' | 'parking' | 'equipment' | 'communication' | 'other';
export type ProjectExpenseStatus = 'draft' | 'submitted' | 'auto_approved' | 'approved' | 'rejected';
export type ProjectLogStatus = 'draft' | 'submitted' | 'approved' | 'rejected';
export type ProjectMaterialStatus = 'planned' | 'reserved' | 'delivered' | 'in_use' | 'completed' | 'returned';
export type ProjectScheduleDayStatus = 'pending' | 'accepted' | 'rejected' | 'modified' | 'completed' | 'cancelled';
export type ProjectWorkerStatus = 'slot' | 'pending' | 'accepted' | 'rejected' | 'active' | 'completed' | 'cancelled';
export type QuantityCalculationType = 'fixed' | 'ratio' | 'formula';
export type QuoteItemBillingUnit = 'unit' | 'hour' | 'day' | 'week' | 'month' | 'flat';
export type QuoteItemType = 'section' | 'item' | 'labor' | 'material';
export type QuoteType = 'sale' | 'rental' | 'event';
export type RateContext = 'internal_cost' | 'customer_billing' | 'payroll';
export type RateType = 'hourly' | 'daily' | 'weekly' | 'monthly' | 'fixed_project';
export type ReturnReason = 'defective' | 'wrong_item' | 'excess' | 'warranty' | 'customer_dissatisfaction' | 'other';
export type SettingType = 'string' | 'number' | 'boolean' | 'json' | 'email' | 'url' | 'color' | 'date' | 'datetime' | 'file' | 'enum';
export type StockMovementType = 'intake' | 'output' | 'transfer' | 'adjustment' | 'return' | 'waste' | 'rental_out' | 'rental_return' | 'site_allocation' | 'site_return' | 'kit_assembly' | 'kit_disassembly';
export type SupplierType = 'materials' | 'personnel' | 'both';
export type WarehouseType = 'central' | 'site_storage' | 'mobile_truck';
export type WorkerType = 'employee' | 'freelancer' | 'external';
}
