declare namespace App.Data {
export type AssignWorkerToServiceData = {
project_worker_id: number;
assigned_hours: number | null;
notes: string | null;
};
export type ChangePasswordData = {
current_password: string;
password: string;
password_confirmation: string | null;
};
export type CompleteInspectionItemData = {
condition: App.Enums.ItemCondition;
quantity_good: number;
quantity_damaged: number;
quantity_write_off: number;
action: App.Enums.InspectionItemAction;
warehouse_id: number;
damage_description: string | null;
repair_estimate: number | null;
};
export type CreateFinalBalanceData = {
title: string;
project_id: number | null;
quote_id: number | null;
customer_id: number | null;
reference_text: string | null;
notes: string | null;
tax_percentage: number;
discount_percentage: number;
is_partial: boolean;
};
export type CreateFinalBalanceItemData = {
type: App.Enums.FinalBalanceItemType;
description: string;
unit: string | null;
quantity: number;
unit_price: number;
cost_price: number | null;
discount_percentage: number;
notes: string | null;
parent_id: number | null;
sort_order: number;
};
export type CreateProjectServiceData = {
description: string;
quantity: number;
unit_price: number;
cost_price: number | null;
billing_unit: string;
is_from_quote: boolean;
quote_item_id: number | null;
status: string;
notes: string | null;
worker_ids: Array<number> | null;
};
export type CreateRepairOrderData = {
product_id: number;
inventory_id: number;
quantity: number;
repair_type: App.Enums.RepairType;
supplier_id: number | null;
incident_id: number | null;
inspection_item_id: number | null;
expected_return_date: string | null;
quarantine_reason: string | null;
};
export type DiscountFamilyData = {
id?: number;
supplier_id: number;
code: string;
name: string;
description: string | null;
discount_1: number;
discount_2: number;
discount_3: number;
is_active: boolean;
};
export type EmailAccountData = {
id?: number;
name: string;
provider: string;
from_email: string;
from_name: string;
smtp_host: string | null;
smtp_port: number | null;
smtp_encryption: string | null;
smtp_username: string | null;
smtp_password: string | null;
oauth_access_token: string | null;
oauth_refresh_token: string | null;
signature: string | null;
signature_plain: string | null;
is_active: boolean;
is_default: boolean;
last_tested_at: string | null;
last_test_success: boolean | null;
last_test_error: string | null;
created_at: string | null;
};
export type EmailLogData = {
id?: number;
email_account_id: number | null;
document_type: string | null;
document_id: number | null;
created_by: number | null;
to_email: string;
to_name: string | null;
subject: string;
status: string;
attempts: number;
last_error: string | null;
sent_at: string | null;
failed_at: string | null;
metadata: Array<any> | null;
created_at: string | null;
updated_at: string | null;
};
export type FinalBalanceData = {
id?: number;
title: string;
project_id: number | null;
quote_id: number | null;
customer_id: number | null;
code?: string;
reference_text: string | null;
notes: string | null;
status?: App.Enums.FinalBalanceStatus;
is_partial: boolean;
is_manual_override: boolean;
subtotal: number;
discount_percentage: number;
discount_amount: number;
tax_percentage: number;
tax_amount: number;
total_amount: number;
issue_date: string | null;
created_by_user_id?: number | null;
finalized_by_user_id?: number | null;
approved_by_user_id?: number | null;
project_name?: string;
customer_name?: string;
items?: Array<App.Data.FinalBalanceItemData>;
};
export type FinalBalanceItemData = {
id?: number;
final_balance_id?: number;
parent_id: number | null;
quote_item_id: number | null;
project_material_id: number | null;
project_service_id: number | null;
project_expense_id: number | null;
incident_id: number | null;
type?: App.Enums.FinalBalanceItemType;
description: string;
code: string | null;
unit: string | null;
quantity: number;
unit_price: number;
cost_price: number | null;
discount_percentage: number;
subtotal: number;
total: number;
is_manual: boolean;
sort_order: number;
notes: string | null;
};
export type FinancialResourceData = {
id?: number;
type: App.Enums.FinancialResourceType;
name: string;
description: string | null;
details: Array<any> | null;
is_active: boolean;
is_default: boolean;
sort_order: number;
notes: string | null;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
display_name?: string;
formatted_bank_info?: string;
formatted_cash_info?: string;
formatted_card_info?: string;
};
export type ForgotPasswordData = {
email: string;
};
export type GenerateFinalBalanceData = {
project_id: number | null;
quote_id: number | null;
customer_id: number | null;
title: string | null;
reference_text: string | null;
notes: string | null;
tax_percentage: number | null;
discount_percentage: number | null;
is_partial: boolean;
include_quote_reference: boolean;
include_extra_materials: boolean;
include_services: boolean;
include_expenses: boolean;
include_damages: boolean;
include_overtime: boolean;
};
export type KitAssemblyData = {
id?: number;
product_id: number;
name: string;
status: App.Enums.KitAssemblyStatus;
warehouse_id: number | null;
location: string | null;
notes: string | null;
assembled_at: string | null;
disassembled_at: string | null;
assembled_by_user_id: number | null;
disassembled_by_user_id: number | null;
created_at?: string;
updated_at?: string;
product?: App.Domains.Product.Data.ProductData | null;
warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
items?: Array<App.Data.KitAssemblyItemData> | null;
};
export type KitAssemblyItemData = {
id?: number;
kit_assembly_id: number;
product_id: number;
quantity: number;
serial_number: string | null;
notes: string | null;
created_at?: string;
updated_at?: string;
product?: App.Domains.Product.Data.ProductData | null;
};
export type PaymentTermData = {
id?: number;
code: string;
name: string;
description: string | null;
days: number;
payment_type: string;
is_default: boolean;
is_active: boolean;
sort_order: number;
};
export type PermissionData = {
name: string;
display_name?: string;
description?: string | null;
guard_name: string;
id?: number;
module?: string;
action?: string;
created_at?: string;
updated_at?: string;
};
export type PriceListData = {
id: number | null;
name: string;
code: string;
description: string | null;
calculation_mode: App.Enums.PriceListCalculationMode;
adjustment_type: App.Enums.PriceListAdjustmentType;
adjustment_value: number | null;
applies_to: App.Enums.PriceListAppliesTo;
category_id: number | null;
department_filter: string | null;
valid_from: string | null;
valid_to: string | null;
is_active: boolean;
is_default: boolean;
priority: number;
category?: App.Domains.Product.Data.ProductCategoryData | null;
items?: Array<App.Data.PriceListItemData> | null;
items_count: number | null;
};
export type PriceListItemData = {
id: number | null;
price_list_id: number;
product_id: number | null;
item_type: string | null;
name: string | null;
code: string | null;
unit: string | null;
vat_rate: number | null;
sale_price: number;
is_manual_price: boolean | null;
rental_daily: number | null;
rental_hourly: number | null;
rental_half_day: number | null;
rental_weekly: number | null;
rental_monthly: number | null;
rental_seasonal: number | null;
is_manual_rental: boolean | null;
is_active: boolean | null;
notes: string | null;
priceList?: App.Data.PriceListData | null;
product?: App.Domains.Product.Data.ProductData | null;
final_sale_price: number | null;
final_rental_daily: number | null;
final_rental_hourly: number | null;
final_rental_half_day: number | null;
final_rental_weekly: number | null;
final_rental_monthly: number | null;
final_rental_seasonal: number | null;
};
export type QuarantinedInventoryData = {
inventory_id: number;
product_id: number;
product_name: string | null;
product_code: string | null;
warehouse_id: number;
quantity_quarantine: number;
quarantine_reason: string | null;
quarantine_since: string | null;
days_in_quarantine: number | null;
repair_order_status: App.Enums.RepairOrderStatus | null;
repair_order_id: number | null;
};
export type RentalProfileData = {
id?: number;
name: string;
sector: string;
exponent_curve: number;
decay_strength: number;
max_duration_reference: number;
duration_offset: number;
max_period_cap_days: number;
is_default: boolean;
is_active: boolean;
created_at: string | null;
updated_at: string | null;
};
export type RepairOrderData = {
id: number | null;
product_id: number;
inventory_id: number;
incident_id: number | null;
inspection_item_id: number | null;
repair_type: App.Enums.RepairType;
supplier_id: number | null;
quantity: number;
sent_date: string | null;
expected_return_date: string | null;
actual_return_date: string | null;
repair_cost: number | null;
repair_notes: string | null;
status: App.Enums.RepairOrderStatus;
created_by_user_id: number;
resolved_by_user_id: number | null;
created_at: string | null;
updated_at: string | null;
product_name: string | null;
product_code: string | null;
supplier_name: string | null;
created_by_name: string | null;
is_overdue: boolean;
};
export type ReportIncidentData = {
project_material_id: number;
incident_type: App.Enums.IncidentType;
description: string;
incident_date: string;
damage_severity: App.Enums.DamageSeverity | null;
charge_amount: number | null;
ddt_item_id: number | null;
quantity: number | null;
};
export type ResetPasswordData = {
email: string;
password: string;
password_confirmation: string | null;
token: string;
};
export type ResolveAvailabilityItemData = {
resolution: App.Enums.AvailabilityResolution;
subrental_supplier_id: number | null;
subrental_estimated_cost: number | null;
notes: string | null;
};
export type ResolveIncidentData = {
resolution_notes: string;
charge_amount: number | null;
is_chargeable_to_client: boolean | null;
};
export type RoleData = {
id?: number;
name: string;
display_name?: string | null;
description?: string | null;
guard_name: string;
permissions: Array<string>;
permissions_count?: number;
users_count?: number;
created_at?: string;
updated_at?: string;
};
export type SettingData = {
id: number | null;
key: string;
value: any;
type: string | null;
group: string | null;
user_id: number | null;
is_public: boolean;
description: string | null;
validation_rules: Array<any> | null;
allowed_values: Array<any> | null;
min_value: number | null;
max_value: number | null;
default_value: any;
order: number;
is_feature_flag: boolean;
created_at: string | null;
updated_at: string | null;
};
export type SubrentalCostHistoryData = {
id?: number;
product_id: number;
supplier_id: number;
quote_id: number | null;
actual_cost: number;
duration_days: number;
margin_generated: number | null;
date: string;
created_at: string | null;
updated_at: string | null;
};
export type SupplierData = {
id?: number;
code: string;
company_name: string;
supplier_type: App.Enums.SupplierType;
personnel_type?: App.Enums.PersonnelType | null;
vat_number?: string | null;
tax_code?: string | null;
email?: string | null;
phone?: string | null;
mobile?: string | null;
website?: string | null;
address?: string | null;
city?: string | null;
province?: string | null;
postal_code?: string | null;
country?: string | null;
payment_terms?: string | null;
delivery_terms?: string | null;
discount_percentage?: number | null;
iban?: string | null;
bank_name?: string | null;
contact_person?: string | null;
contact_email?: string | null;
contact_phone?: string | null;
notes?: string | null;
specializations?: Array<any> | null;
is_active: boolean;
created_at?: string;
updated_at?: string;
deleted_at?: string | null;
};
export type SupplierProductData = {
id: number | null;
supplier_id: number;
product_id: number;
supplier_product_code: string | null;
supplier_ean: string | null;
purchase_price: number;
wholesale_price: number | null;
retail_price: number | null;
discount_family_id: number | null;
manual_discount_1: number | null;
manual_discount_2: number | null;
manual_discount_3: number | null;
package_quantity: number | null;
minimum_order_quantity: number | null;
maximum_order_quantity: number | null;
multiple_order_quantity: number | null;
lead_time_days: number | null;
payment_term_id: number | null;
price_multiplier: number | null;
currency: string | null;
last_price_update: string | null;
is_preferred_supplier: boolean | null;
is_active: boolean | null;
notes: string | null;
supplier?: App.Data.SupplierData | null;
product?: App.Domains.Product.Data.ProductData | null;
discountFamily?: App.Data.DiscountFamilyData | null;
paymentTerm?: App.Data.PaymentTermData | null;
final_price: number | null;
effective_discounts: Array<any> | null;
created_at: string | null;
updated_at: string | null;
};
export type UpdateFinalBalanceData = {
title?: string;
project_id?: number | null;
quote_id?: number | null;
customer_id?: number | null;
reference_text?: string | null;
notes?: string | null;
tax_percentage?: number;
discount_percentage?: number;
is_partial?: boolean;
is_manual_override?: boolean;
issue_date?: string | null;
};
export type UpdateFinalBalanceItemData = {
type?: App.Enums.FinalBalanceItemType;
description?: string;
unit?: string | null;
quantity?: number;
unit_price?: number;
cost_price?: number | null;
discount_percentage?: number;
notes?: string | null;
sort_order?: number;
};
export type UpdateProjectServiceData = {
description: string | null;
quantity: number | null;
unit_price: number | null;
cost_price: number | null;
billing_unit: string | null;
is_from_quote: boolean | null;
quote_item_id: number | null;
status: string | null;
notes: string | null;
worker_ids: Array<number> | null;
};
export type UpdateRepairOrderStatusData = {
status: App.Enums.RepairOrderStatus;
actual_return_date: string | null;
repair_cost: number | null;
repair_notes: string | null;
};
export type UserData = {
name: string;
email: string;
is_active: boolean;
roles: Array<string>;
id?: number;
password?: string | null;
password_confirmation?: string | null;
permissions?: Array<any>;
worker: any;
created_at?: string;
updated_at?: string;
};
export type WarrantyTypeData = {
id?: number;
name: string;
years: number | null;
description: string | null;
exclusions: Array<string> | null;
is_default: boolean;
is_active: boolean;
sort_order: number;
};
}
declare namespace App.Data.Landlord {
export type AddMembershipData = {
tenant_id: string;
role: string;
};
export type GlobalUserData = {
id?: string;
name: string;
email: string;
phone: string | null;
tax_code: string | null;
fiscal_code: string | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
country: string | null;
iban: string | null;
is_landlord_admin: boolean | null;
email_verified_at: string | null;
created_at?: string;
tenants_count?: number;
};
export type PlanData = {
id?: number;
name: string;
slug: string;
description: string | null;
price: number | null;
price_yearly: number | null;
is_active: boolean;
sort_order: number;
trial_days: number;
features?: Array<App.Data.Landlord.PlanFeatureData> | null;
};
export type PlanFeatureData = {
id?: number;
plan_id?: number;
feature_key: string;
price: number | null;
price_yearly: number | null;
limits: Array<any> | null;
};
export type RenewalRequestData = {
id?: number;
tenant_id: string;
tenant_subscription_id: number;
type: string;
status: string;
requested_by_global_user_id: string | null;
addons: Array<any> | null;
target_plan_id: number | null;
prorated_amount: number | null;
cycle_days_total: number | null;
cycle_days_remaining: number | null;
billing_cycle: string | null;
notes: string | null;
admin_notes: string | null;
processed_at: string | null;
processed_by_global_user_id: string | null;
created_at?: string;
subscription?: App.Data.Landlord.TenantSubscriptionData | null;
};
export type TenantData = {
id?: string;
name: string;
slug: string | null;
created_at?: string;
bootstrap_status: App.Enums.BootstrapStatus | null;
subscription?: App.Data.Landlord.TenantSubscriptionData | null;
};
export type TenantMembershipData = {
id?: number;
global_user_id: string;
tenant_id: string;
role: string;
status: string;
created_at?: string;
};
export type TenantMembershipWithTenantData = {
id?: number;
tenant_id: string;
tenant_name: string;
role: string;
status: string;
created_at?: string;
};
export type TenantOverviewItemData = {
tenant_id: string;
tenant_name: string;
role: string;
worker_id: number | null;
projects_count: number;
};
export type TenantSubscriptionData = {
id?: number;
tenant_id: string;
plan_id: number | null;
status: string;
starts_at: string | null;
ends_at: string | null;
trial_ends_at: string | null;
billing_cycle: string;
renews_at: string | null;
notes: string | null;
created_at?: string;
plan?: App.Data.Landlord.PlanData | null;
addons?: Array<App.Data.Landlord.TenantSubscriptionFeatureData> | null;
total_price: number | null;
};
export type TenantSubscriptionFeatureData = {
id?: number;
feature_key: string;
price_at_purchase: number | null;
};
}
declare namespace App.Domains.Customer.Data {
export type CustomerData = {
id?: number;
type: App.Enums.CustomerType;
first_name: string | null;
last_name: string | null;
company_name: string | null;
vat_number: string | null;
tax_code: string | null;
email: string | null;
phone: string | null;
mobile: string | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
country: string | null;
payment_terms: string | null;
discount_percentage: number | null;
notes: string | null;
is_active: boolean | null;
display_name: string | null;
};
}
declare namespace App.Domains.Product.Data {
export type ProductBrandData = {
id?: number;
name: string;
code?: string;
description: string | null;
logo_url: string | null;
website: string | null;
is_active?: boolean;
};
export type ProductCategoryData = {
id: number | null;
code: string;
name: string;
description: string | null;
icon: string | null;
color: string | null;
sort_order?: number;
is_active?: boolean;
rental_profile_id: number | null;
rentalProfile: App.Data.RentalProfileData | null;
};
export type ProductComponentData = {
id?: number;
kit_product_id: number;
component_product_id: number;
quantity: number;
notes?: string | null;
created_at?: string;
updated_at?: string;
};
export type ProductData = {
id?: number;
code: string;
internal_code: string | null;
ean: string | null;
etim_code: string | null;
name: string;
description: string | null;
category_id: number | null;
brand_id: number | null;
product_type: App.Domains.Product.Enums.ProductType;
kit_type: App.Enums.KitType | null;
is_package?: boolean;
package_weight: number | null;
package_volume: number | null;
package_dimensions: string | null;
is_rentable?: boolean;
ownership_type?: string;
is_premium?: boolean;
subrental_markup: number | null;
rental_price_estimated?: boolean;
estimated_base_day: number | null;
unit: string | null;
standard_cost: number | null;
manufacturer_cost_price: number | null;
manufacturer_retail_price: number | null;
sale_markup_percent: number | null;
barcode: string | null;
qr_code: string | null;
default_supplier_id: number | null;
reorder_level: number | null;
reorder_quantity: number | null;
lead_time_days: number | null;
location: string | null;
notes: string | null;
is_active: boolean | null;
is_labor_role: boolean;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
category?: App.Domains.Product.Data.ProductCategoryData | null;
brand?: App.Domains.Product.Data.ProductBrandData | null;
defaultSupplier?: App.Data.SupplierData | null;
relations?: Array<App.Domains.Product.Data.ProductRelationData> | null;
media?: Array<App.Domains.Product.Data.ProductMediaData> | null;
priceListItems?: Array<App.Data.PriceListItemData> | null;
composite_total_cost?: number;
total_stock?: number;
total_out_on_rental?: number;
available_stock?: number;
};
export type ProductMediaData = {
id?: number;
collection_name: string;
file_name?: string;
mime_type?: string;
size?: number;
url?: string;
thumb_url?: string | null;
medium_url?: string | null;
description: string | null;
is_primary?: boolean;
use_in_quotes?: boolean;
use_in_projects?: boolean;
document_type: string | null;
valid_until: string | null;
sort_order?: number;
created_at?: string;
is_pdf_conversion?: boolean;
pdf_media_id: number | null;
pdf_url: string | null;
};
export type ProductRelationData = {
id: number | null;
product_id: number;
related_product_id: number;
relation_type_id: number;
quantity_type: App.Domains.Product.Enums.ProductRelationQuantityType;
quantity_value: string;
is_visible_in_quote: boolean;
is_visible_in_material_list: boolean;
is_required_for_stock: boolean;
is_optional: boolean;
min_quantity_trigger: number | null;
max_quantity_trigger: number | null;
sort_order: number | null;
notes: string | null;
relatedProduct?: App.Domains.Product.Data.ProductData | null;
relationType?: App.Domains.Product.Data.ProductRelationTypeData | null;
};
export type ProductRelationTypeData = {
id: number | null;
code: string;
name: string;
description: string | null;
icon: string | null;
color: string | null;
sort_order: number;
is_active: boolean;
};
export type ProductSubrentalSupplierData = {
id?: number;
product_id: number;
supplier_id: number;
day_rate: number | null;
reliability_score: number;
is_preferred: boolean;
last_updated: string | null;
notes: string | null;
created_at?: string;
updated_at?: string;
product?: App.Domains.Product.Data.ProductData | null;
supplier?: App.Data.SupplierData | null;
};
export type ProductUnitTypeData = {
id: number | null;
code: string;
name_it: string;
symbol_it: string;
name_en: string;
symbol_en: string;
aliases: Array<any> | null;
category: string | null;
conversion_factor: number | null;
is_active: boolean | null;
sort_order: number | null;
};
}
declare namespace App.Domains.Product.Enums {
export type ProductRelationQuantityType = 'fixed' | 'multiplied' | 'formula';
export type ProductType = 'article' | 'service' | 'composite' | 'kit';
}
declare namespace App.Domains.Project.Data {
export type ExpensePnlData = {
};
export type ProjectAvailabilityCheckData = {
id: number;
project_id: number;
status: App.Enums.AvailabilityCheckStatus;
checked_at: string;
checked_by_user_id: number | null;
notes: string | null;
items: Array<App.Domains.Project.Data.ProjectAvailabilityCheckItemData>;
available_count: number;
partial_count: number;
unavailable_count: number;
resolved_count: number;
};
export type ProjectAvailabilityCheckItemData = {
id: number;
check_id: number;
project_material_id: number;
planned_qty: number;
available_qty: number;
reserved_qty: number;
shortage_qty: number;
availability_status: App.Enums.AvailabilityStatus;
resolution: App.Enums.AvailabilityResolution;
subrental_supplier_id: number | null;
subrental_estimated_cost: number | null;
resolved_at: string | null;
resolved_by_user_id: number | null;
product_name: string | null;
product_code: string | null;
unit: string | null;
};
export type ProjectData = {
id: number | null;
code: string | null;
name: string;
description: string | null;
customer_id: number;
quote_id: number | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
country: string | null;
latitude: number | null;
longitude: number | null;
gps_radius: number | null;
project_manager_id: number | null;
estimated_amount: number | null;
actual_cost: number | null;
invoiced_amount: number | null;
start_date: string | null;
estimated_end_date: string | null;
actual_end_date: string | null;
status: string;
priority: string | null;
notes: string | null;
internal_notes: string | null;
is_active: boolean;
customer: App.Domains.Customer.Data.CustomerData | null;
};
export type ProjectExpenseData = {
id: number | null;
project_id: number;
project_worker_id: number | null;
submitted_by_user_id: number | null;
category: App.Enums.ProjectExpenseCategory;
description: string;
amount: number;
expense_date: string;
is_billable_to_client: boolean;
receipt_media_id: number | null;
status: App.Enums.ProjectExpenseStatus;
approved_by_user_id: number | null;
approved_at: string | null;
rejection_reason: string | null;
notes: string | null;
is_budgeted: boolean | null;
budgeted_amount: number | null;
billable_to_final_balance: boolean | null;
submitted_by_name: string | null;
category_label: string | null;
variance: number | null;
receipt_url: string | null;
};
export type ProjectLaborCostData = {
id: number | null;
project_id: number | null;
cost_type: string | null;
worker_id: number | null;
contractor_id: number | null;
description: string | null;
work_date: string | null;
hours_worked: number | null;
quantity: number | null;
unit_rate: number | null;
total_cost: number | null;
currency: string | null;
is_overtime: boolean;
is_holiday: boolean;
cost_category: string | null;
invoice_number: string | null;
invoice_date: string | null;
is_invoiced: boolean;
notes: string | null;
};
export type ProjectLaborLogData = {
id: number | null;
project_id: number;
project_worker_id: number;
worker_id: number | null;
schedule_day_id: number | null;
log_date: string;
clock_in: string | null;
clock_out: string | null;
break_minutes: number;
regular_hours: number;
overtime_hours: number;
description: string | null;
submitted_by_user_id: number | null;
status: App.Enums.ProjectLogStatus;
approved_by_user_id: number | null;
approved_at: string | null;
rejection_reason: string | null;
labor_cost_id: number | null;
overtime_cause: App.Enums.OvertimeCause | null;
is_billable_to_client: boolean | null;
overtime_rate_multiplier: number | null;
include_in_final_balance: boolean | null;
overtime_rate_type: string | null;
overtime_direct_rate: number | null;
is_auto_approved: boolean;
total_hours: number | null;
submitted_by_name: string | null;
worker_name: string | null;
};
export type ProjectMaterialData = {
id: number | null;
project_id: number | null;
product_id: number | null;
quote_item_id: number | null;
is_extra: boolean | null;
requested_by: number | null;
requested_at: string | null;
extra_reason: string | null;
planned_quantity: number | null;
allocated_quantity: number | null;
delivered_quantity: number | null;
used_quantity: number | null;
returned_quantity: number | null;
planned_unit_cost: number | null;
actual_unit_cost: number | null;
status: App.Enums.ProjectMaterialStatus | null;
required_date: string | null;
delivery_date: string | null;
notes: string | null;
kit_assembly_id: number | null;
is_rental: boolean | null;
subrental_assignments: Array<any> | null;
remaining_quantity: number | null;
usage_percentage: number | null;
planned_total_cost: number | null;
actual_total_cost: number | null;
cost_variance: number | null;
product_name: string | null;
product_code: string | null;
product?: App.Domains.Product.Data.ProductData | null;
quoteItem?: App.Domains.Quote.Data.QuoteItemData | null;
kit_assembly?: App.Data.KitAssemblyData | null;
};
export type ProjectMaterialIncidentData = {
id: number | null;
project_id: number;
project_material_id: number;
incident_type: App.Enums.IncidentType;
damage_severity: App.Enums.DamageSeverity | null;
description: string;
incident_date: string;
is_chargeable_to_client: boolean;
charge_amount: number | null;
charge_basis: string | null;
status: App.Enums.IncidentStatus;
resolution_notes: string | null;
reported_by_user_id: number | null;
resolved_by_user_id: number | null;
resolved_at: string | null;
ddt_item_id: number | null;
product_name: string | null;
reported_by_name: string | null;
resolved_by_name: string | null;
incident_photos_count: number;
};
export type ProjectPnlData = {
project_id: number;
project_name: string;
project_code: string;
customer_name: string | null;
quote_total: number;
quote_labor_total: number;
quote_material_total: number;
extra_labor_revenue: number;
billable_expenses_revenue: number;
total_revenue: number;
labor_cost_total: number;
external_labor_cost: number;
internal_labor_cost: number;
material_cost_total: number;
approved_expenses_total: number;
total_cost: number;
gross_margin: number;
gross_margin_percent: number;
workers?: Array<App.Domains.Project.Data.WorkerPnlData>;
expenses?: Array<App.Domains.Project.Data.ExpensePnlData>;
generated_at: string | null;
};
export type ProjectRoleData = {
id: number | null;
name: string;
slug: string | null;
description: string | null;
color: string | null;
sort_order: number | null;
is_active: boolean;
};
export type ProjectServiceData = {
id: number | null;
project_id: number | null;
description: string;
quantity: number;
unit_price: number;
cost_price: number | null;
billing_unit: string;
is_from_quote: boolean;
quote_item_id: number | null;
status: string;
notes: string | null;
created_by_user_id: number | null;
created_by_name: string | null;
total: number | null;
margin: number | null;
margin_percentage: number | null;
workers: { [key: number]: { [key: string]: any } } | null;
};
export type ProjectStockData = {
project_material_id: number;
product_id: number;
product_name: string;
product_code: string;
unit: string | null;
is_rentable: boolean;
is_consumable: boolean;
project_stock: number;
delivered_quantity: number;
used_quantity: number;
returned_quantity: number;
required_return_date: string | null;
};
export type ProjectStockSummaryData = {
total_items_on_site: number;
total_value_on_site: number;
overdue_rental_items_count: number;
};
export type ProjectWorkerData = {
id: number | null;
project_id: number | null;
worker_id: number | null;
status: string | null;
assigned_by_user_id: number | null;
site_role: string | null;
assigned_from: string | null;
assigned_to: string | null;
responded_at: string | null;
response_due_at: string | null;
rejection_reason: string | null;
hourly_rate_override: number | null;
fixed_rate_override: number | null;
rate_override_notes: string | null;
estimated_hours: number | null;
is_active: boolean;
notes: string | null;
role_name: string | null;
slot_index: number;
quote_item_id: number | null;
estimated_days: number | null;
budget_cost_rate: number | null;
actual_cost_rate: number | null;
customer_rate: number | null;
is_external: boolean;
is_scheduled: boolean;
worker_name: string | null;
worker_code: string | null;
roles: Array<any> | null;
};
export type ProjectWorkerScheduleData = {
id: number | null;
project_id: number;
worker_id: number;
scheduled_date: string;
planned_start_time: string | null;
planned_end_time: string | null;
planned_hours: number | null;
status: App.Enums.ProjectScheduleDayStatus;
accepted_at: string | null;
rejected_at: string | null;
rejection_reason: string | null;
notes: string | null;
cost_rate: number | null;
customer_rate: number | null;
effective_planned_hours: number | null;
};
export type WorkerPnlData = {
};
}
declare namespace App.Domains.Quote.Data {
export type QuoteData = {
title: string;
customer_id: number;
id?: number;
code?: string;
project_manager_id: number | null;
description: string | null;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
status: string;
quote_type: App.Enums.QuoteType;
event_days: number | null;
issue_date: string | null;
expiry_date: string | null;
sent_date: string | null;
approved_date: string | null;
price_list_id: number | null;
payment_term_id: number | null;
financial_resource_id: number | null;
template_id: number | null;
project_id: number | null;
warranty_type_id: number | null;
subtotal: number;
discount_percentage: number;
discount_amount: number;
tax_percentage: number;
tax_amount: number;
total_amount: number;
deposit_percentage: number | null;
deposit_amount: number | null;
balance_label: string | null;
work_start_description: string | null;
work_start_date: string | null;
work_duration_description: string | null;
work_end_date: string | null;
tax_included: boolean;
show_unit_prices: boolean;
show_product_codes: boolean;
show_vat: boolean;
show_section_totals: boolean;
vat_included_in_prices: boolean;
include_terms_and_conditions: boolean;
notes: string | null;
terms_and_conditions: string | null;
footer_text: string | null;
customer?: App.Domains.Customer.Data.CustomerData;
projectManager?: App.Data.UserData;
priceList?: App.Data.PriceListData;
paymentTerm?: App.Data.PaymentTermData;
financialResource?: App.Data.FinancialResourceData;
warrantyType?: App.Data.WarrantyTypeData;
project?: App.Domains.Project.Data.ProjectData;
items?: Array<App.Domains.Quote.Data.QuoteItemData>;
deposits?: Array<App.Domains.Quote.Data.QuoteDepositData>;
full_address?: string;
};
export type QuoteDepositData = {
id?: number;
sort_order: number;
description: string;
percentage: number | null;
amount: number | null;
is_fixed_amount: boolean;
due_date: string | null;
due_event: string | null;
};
export type QuoteItemData = {
type: App.Enums.QuoteItemType;
description: string;
id?: number;
quote_id: number | null;
parent_id: number | null;
product_id: number | null;
price_list_item_id: number | null;
code: string | null;
notes: string | null;
sort_order: number;
unit: string | null;
billing_unit: App.Enums.QuoteItemBillingUnit;
duration: number | null;
quantity: number | null;
unit_price: number | null;
cost_price: number | null;
discount_percentage: number;
subtotal: number;
discount_amount: number;
total: number;
vat_rate: number | null;
vat_amount: number;
total_with_vat: number;
hide_unit_price: boolean;
include_image: boolean;
included_media_ids: Array<number> | null;
expand_kit: boolean;
product?: App.Domains.Product.Data.ProductData;
priceListItem?: App.Data.PriceListItemData;
parent?: App.Domains.Quote.Data.QuoteItemData;
children?: Array<App.Domains.Quote.Data.QuoteItemData>;
margin_amount: number | null;
margin_percent: number | null;
};
}
declare namespace App.Domains.Warehouse.Data {
export type DdtData = {
id?: number;
code?: string;
type: App.Enums.DdtType;
supplier_id: number | null;
customer_id: number | null;
project_id: number | null;
price_list_id: number | null;
from_warehouse_id: number;
to_warehouse_id: number | null;
ddt_number: string;
ddt_date: string;
transport_date: string | null;
delivered_at: string | null;
carrier_name: string | null;
tracking_number: string | null;
rental_start_date: string | null;
rental_end_date: string | null;
rental_actual_return_date: string | null;
parent_ddt_id: number | null;
return_reason: App.Enums.ReturnReason | null;
return_notes: string | null;
status: App.Enums.DdtStatus | null;
notes: string | null;
created_by: number | null;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
supplier?: App.Data.SupplierData | null;
customer?: App.Domains.Customer.Data.CustomerData | null;
project?: App.Domains.Project.Data.ProjectData | null;
price_list?: App.Data.PriceListData | null;
from_warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
to_warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
created_by_user?: App.Data.UserData | null;
parent_ddt?: App.Domains.Warehouse.Data.DdtData | null;
items?: Array<App.Domains.Warehouse.Data.DdtItemData>;
stock_movements?: Array<App.Domains.Warehouse.Data.StockMovementData> | null;
total_items: number;
total_quantity: number;
can_be_confirmed: boolean;
can_be_cancelled: boolean;
is_delivered: boolean;
};
export type DdtItemData = {
id?: number;
ddt_id?: number | null;
product_id: number;
quantity: number;
unit: string;
unit_cost: number | null;
notes: string | null;
kit_assembly_id: number | null;
created_at?: string;
updated_at?: string;
product?: App.Domains.Product.Data.ProductData | null;
kit_assembly?: App.Data.KitAssemblyData | null;
total_cost: number;
};
export type InventoryData = {
id?: number;
product_id: number;
warehouse_id: number;
quantity_available: number | null;
quantity_reserved: number | null;
quantity_out_on_rental: number;
quantity_in_transit: number | null;
quantity_quarantine: number | null;
minimum_stock: number | null;
maximum_stock: number | null;
last_count_date: string | null;
created_at?: string;
updated_at?: string;
product?: App.Domains.Product.Data.ProductData | null;
warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
quantity_free: number;
is_low_stock: boolean;
stock_value: number;
};
export type InventoryReservationData = {
id?: number;
product_id: number;
warehouse_id: number | null;
quantity: number;
start_date: string;
end_date: string | null;
type: App.Enums.InventoryReservationType;
reference_type: string | null;
reference_id: number | null;
status: App.Enums.InventoryReservationStatus;
notes: string | null;
created_at?: string;
updated_at?: string;
warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
};
export type RentalReturnInspectionData = {
id: number;
ddt_id: number;
project_id: number | null;
inspected_by_user_id: number;
inspection_date: string;
status: App.Enums.InspectionStatus;
overall_notes: string | null;
items: Array<App.Domains.Warehouse.Data.RentalReturnInspectionItemData>;
total_damage_value: number;
total_write_off_value: number;
inspected_by_name: string | null;
project_name: string | null;
ddt_code: string | null;
};
export type RentalReturnInspectionItemData = {
id: number;
inspection_id: number;
ddt_item_id: number;
product_id: number;
total_quantity: number;
quantity_good: number;
quantity_damaged: number;
quantity_write_off: number;
condition: App.Enums.ItemCondition | null;
damage_description: string | null;
repair_estimate: number | null;
action: App.Enums.InspectionItemAction | null;
incident_id: number | null;
warehouse_id: number | null;
product_name: string | null;
product_code: string | null;
warehouse_name: string | null;
is_reviewed: boolean;
};
export type StockMovementData = {
id?: number;
code?: string;
ddt_id: number | null;
product_id: number;
warehouse_id: number;
type: App.Enums.StockMovementType;
quantity: number;
unit_cost: number | null;
movement_date: string;
from_warehouse_id: number | null;
to_warehouse_id: number | null;
project_id: number | null;
supplier_id: number | null;
supplier_document: string | null;
user_id: number | null;
notes: string | null;
reference_document: string | null;
created_at?: string;
updated_at?: string;
product?: App.Domains.Product.Data.ProductData | null;
warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
from_warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
to_warehouse?: App.Domains.Warehouse.Data.WarehouseData | null;
project: any | null;
supplier?: App.Data.SupplierData | null;
user?: App.Data.UserData | null;
ddt: any | null;
total_value: number;
type_label: string;
type_color: string;
is_outgoing: boolean;
is_incoming: boolean;
};
export type WarehouseData = {
id: number | null;
code: string | null;
name: string;
type: App.Enums.WarehouseType;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
manager_id: number | null;
notes: string | null;
is_active: boolean;
full_address: string | null;
total_value?: number | null;
manager?: App.Data.UserData | null;
};
}
declare namespace App.Enums {
export type AvailabilityCheckStatus = 'pending' | 'completed' | 'resolved';
export type AvailabilityResolution = 'none' | 'reserve_existing' | 'subrental' | 'remove_from_project';
export type AvailabilityStatus = 'available' | 'partial' | 'unavailable';
export type BootstrapStatus = 'pending' | 'database_created' | 'migrated' | 'storage_ready' | 'seeded' | 'bootstrapping' | 'ready' | 'failed';
export type ContractType = 'permanent' | 'fixed_term' | 'seasonal' | 'project_based' | 'internship';
export type ContractorType = 'cooperative' | 'subcontractor' | 'temporary_agency';
export type CustomerType = 'individual' | 'company';
export type DamageSeverity = 'minor' | 'major' | 'write_off';
export type DdtStatus = 'draft' | 'issued' | 'in_transit' | 'delivered' | 'cancelled';
export type DdtType = 'incoming' | 'outgoing' | 'internal' | 'rental_out' | 'rental_return' | 'return_from_customer' | 'return_to_supplier';
export type DependencyType = 'container' | 'accessory' | 'cable' | 'consumable' | 'tool';
export type DocumentType = 'quote' | 'invoice' | 'ddt' | 'sal' | 'invitation' | 'generic';
export type FinalBalanceItemType = 'section' | 'material' | 'labor' | 'expense' | 'service' | 'damage' | 'transport' | 'quote_reference' | 'other';
export type FinalBalanceStatus = 'draft' | 'finalized' | 'approved';
export type FinancialResourceType = 'bank_account' | 'cash' | 'card';
export type IncidentStatus = 'open' | 'reviewed' | 'resolved' | 'invoiced';
export type IncidentType = 'missing' | 'broken' | 'damaged' | 'contaminated' | 'lost_by_client' | 'stolen';
export type InspectionItemAction = 'return_to_stock' | 'quarantine' | 'write_off';
export type InspectionStatus = 'in_progress' | 'completed';
export type InventoryReservationStatus = 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled';
export type InventoryReservationType = 'rental_booking' | 'project_material' | 'sale_order';
export type ItemCondition = 'good' | 'minor_damage' | 'major_damage' | 'write_off';
export type KitAssemblyStatus = 'assembled' | 'in_use' | 'returned' | 'disassembled';
export type KitType = 'distributed' | 'assembled';
export type LaborCostType = 'internal_labor' | 'subcontractor' | 'contractor';
export type MaterialRequestPriority = 'low' | 'medium' | 'high' | 'urgent';
export type MaterialRequestStatus = 'pending' | 'approved' | 'rejected' | 'delivered';
export type OvertimeCause = 'client_request' | 'project_delay_our_fault' | 'project_delay_client_fault' | 'weather' | 'unforeseen';
export type PaymentMethod = 'bank_transfer' | 'credit_card' | 'debit_card' | 'cash' | 'check' | 'riba' | 'rid' | 'paypal' | 'sepa_dd' | 'wire_transfer';
export type PayrollFrequency = 'monthly' | 'biweekly' | 'weekly';
export type PersonnelType = 'cooperative' | 'staffing_agency' | 'rental_with_operator' | 'subcontractor' | 'technical_services';
export type PriceListAdjustmentType = 'percentage' | 'fixed' | 'none' | 'multiplier';
export type PriceListAppliesTo = 'sale' | 'rental' | 'both';
export type PriceListCalculationMode = 'automatic' | 'manual';
export type ProjectExpenseCategory = 'travel' | 'accommodation' | 'meal' | 'fuel' | 'toll' | 'parking' | 'equipment' | 'communication' | 'mileage_reimbursement' | 'flight' | 'train' | 'ferry' | 'taxi' | 'equipment_rental' | 'other';
export type ProjectExpenseStatus = 'draft' | 'submitted' | 'auto_approved' | 'approved' | 'rejected';
export type ProjectLogStatus = 'draft' | 'submitted' | 'approved' | 'rejected';
export type ProjectMaterialStatus = 'planned' | 'reserved' | 'delivered' | 'in_use' | 'completed' | 'returned';
export type ProjectScheduleDayStatus = 'pending' | 'accepted' | 'rejected' | 'modified' | 'completed' | 'cancelled';
export type ProjectServiceBillingUnit = 'hour' | 'day' | 'flat';
export type ProjectServiceStatus = 'planned' | 'in_progress' | 'completed' | 'cancelled';
export type ProjectWorkerStatus = 'slot' | 'pending' | 'accepted' | 'rejected' | 'active' | 'completed' | 'cancelled';
export type QuantityCalculationType = 'fixed' | 'ratio' | 'formula';
export type QuoteItemBillingUnit = 'unit' | 'hour' | 'day' | 'week' | 'month' | 'flat';
export type QuoteItemType = 'section' | 'item' | 'labor' | 'material';
export type QuoteType = 'sale' | 'rental' | 'event';
export type RateContext = 'internal_cost' | 'customer_billing' | 'payroll';
export type RateType = 'hourly' | 'daily' | 'weekly' | 'monthly' | 'fixed_project';
export type RepairOrderStatus = 'pending' | 'sent_external' | 'in_repair' | 'completed' | 'unrepairable';
export type RepairType = 'internal' | 'external';
export type ReturnReason = 'defective' | 'wrong_item' | 'excess' | 'warranty' | 'customer_dissatisfaction' | 'other';
export type SettingType = 'string' | 'number' | 'boolean' | 'json' | 'email' | 'url' | 'color' | 'date' | 'datetime' | 'file' | 'enum';
export type StockMovementType = 'intake' | 'output' | 'transfer' | 'adjustment' | 'return' | 'waste' | 'rental_out' | 'rental_return' | 'site_allocation' | 'site_return' | 'kit_assembly' | 'kit_disassembly';
export type SupplierType = 'materials' | 'personnel' | 'both';
export type WarehouseType = 'central' | 'site_storage' | 'mobile_truck';
export type WorkerType = 'employee' | 'freelancer' | 'external';
}
