'use client';

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { suppliersApi } from '@/lib/api/suppliers';
// TODO: Create generateProductCode utility function
// import { generateProductCode } from '@/lib/utils/code-generator';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { ComboboxSelect } from '@/components/combobox-select';
import { ProductCategoryCombobox } from './product-category-combobox';
import { BarcodeScanner } from '@/components/barcode-scanner';
import { Scan } from 'lucide-react';
import type { ProductType, ProductFormData } from "@/lib/types";

// TODO: Move to lib/utils/code-generator.ts
function generateProductCode(name: string): string {
  const prefix = 'PROD';
  const namePart = name
    .split(' ')
    .slice(0, 2)
    .map(word => word.substring(0, 3).toUpperCase())
    .join('');
  const timestamp = Date.now().toString().slice(-6);
  return `${prefix}-${namePart}-${timestamp}`;
}

// Form data locale per il form (estende ProductFormData con campi opzionali)
type ProductFormDataLocal = ProductFormData & {
  quantity_out_on_rental?: number;
};

interface ProductFormProps {
  initialData?: Partial<ProductFormDataLocal>;
  onSubmit: (data: ProductFormData) => void;
  onCancel: () => void;
  isSubmitting?: boolean;
  mode: 'create' | 'edit';
}

const unitOptions = [
  { value: 'pz', label: 'Pezzi (pz)' },
  { value: 'kg', label: 'Kilogrammi (kg)' },
  { value: 'm', label: 'Metri (m)' },
  { value: 'm²', label: 'Metri quadri (m²)' },
  { value: 'm³', label: 'Metri cubi (m³)' },
  { value: 'l', label: 'Litri (l)' },
  { value: 'conf', label: 'Confezione (conf)' },
  { value: 'cad', label: 'Cadauno (cad)' },
];

export function ProductForm({
  initialData,
  onSubmit,
  onCancel,
  isSubmitting = false,
  mode,
}: ProductFormProps) {
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(mode === 'create' && !initialData?.code);
  const [scannerOpen, setScannerOpen] = useState(false);
  const [formData, setFormData] = useState<ProductFormDataLocal>({
    code: initialData?.code || '',
    name: initialData?.name || '',
    description: initialData?.description ?? null,
    category_id: initialData?.category_id ?? null,
    product_type: initialData?.product_type || 'article',
    unit: initialData?.unit || 'pz',
    is_package: initialData?.is_package || false,
    package_weight: initialData?.package_weight ?? null,
    package_volume: initialData?.package_volume ?? null,
    package_dimensions: initialData?.package_dimensions ?? null,
    is_rentable: initialData?.is_rentable || false,
    quantity_out_on_rental: initialData?.quantity_out_on_rental || 0,
    standard_cost: initialData?.standard_cost || 0,
    purchase_price: initialData?.purchase_price || 0,
    markup_percentage: initialData?.markup_percentage || 0,
    sale_price: initialData?.sale_price || 0,
    rental_price_daily: initialData?.rental_price_daily || 0,
    rental_price_weekly: initialData?.rental_price_weekly || 0,
    rental_price_monthly: initialData?.rental_price_monthly || 0,
    barcode: initialData?.barcode ?? null,
    qr_code: initialData?.qr_code ?? null,
    default_supplier_id: initialData?.default_supplier_id ?? null,
    reorder_level: initialData?.reorder_level || 0,
    reorder_quantity: initialData?.reorder_quantity || 0,
    lead_time_days: initialData?.lead_time_days || 7,
    location: initialData?.location ?? null,
    notes: initialData?.notes ?? null,
    is_active: initialData?.is_active ?? true,
  });

  const [supplierSearch, setSupplierSearch] = useState('');

  // Load suppliers - always show initial list, then filter by search
  const { data: suppliersData, isLoading: isLoadingSuppliers } = useQuery({
    queryKey: ['suppliers', { is_active: true, search: supplierSearch }],
    queryFn: () =>
      suppliersApi.getAll({
        is_active: true,
        search: supplierSearch || undefined,
        per_page: 50,
      }),
    // Always fetch - even without search, to show initial list
  });

  const suppliers = suppliersData?.data ?? [];

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Converti al formato ProductFormData per il backend
    const submitData: ProductFormData = {
      ...formData,
      category_id: formData.category_id ?? null,
      product_type: formData.product_type || 'article',
      rental_price_daily: formData.rental_price_daily || 0,
      rental_price_weekly: formData.rental_price_weekly || 0,
      rental_price_monthly: formData.rental_price_monthly || 0,
    };

    onSubmit(submitData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Informazioni Generali */}
      <Card>
        <CardHeader>
          <CardTitle>Informazioni Generali</CardTitle>
          <CardDescription>Dati identificativi del producte</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="code">
                Codice {mode === 'create' && '(opzionale - autogenerato)'}
              </Label>
              <Input
                id="code"
                value={formData.code}
                onChange={(e) => {
                  const newCode = e.target.value;
                  setFormData({ ...formData, code: newCode });
                  // If user manually edits code, disable auto-generation
                  if (mode === 'create') {
                    setIsCodeAutoGenerated(false);
                  }
                }}
                placeholder="MAT-001"
                className="h-11"
              />
              <p className="text-xs text-slate-500">
                {mode === 'create' && isCodeAutoGenerated
                  ? 'Si genera automaticamente dal nome'
                  : 'Se vuoto, verrà generato automaticamente'}
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="name" className="required">
                Nome Materiale *
              </Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => {
                  const newName = e.target.value;
                  setFormData({ ...formData, name: newName });

                  // Auto-generate code only in create mode and if not manually edited
                  if (mode === 'create' && isCodeAutoGenerated && newName) {
                    const generatedCode = generateProductCode(newName);
                    setFormData((prev: ProductFormDataLocal) => ({ ...prev, name: newName, code: generatedCode }));
                  }
                }}
                placeholder="Es: Cemento Portland CEM II/A-L 42,5 R"
                required
                className="h-11"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Descrizione</Label>
            <Textarea
              id="description"
              value={formData.description || ""}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Descrizione dettagliata del producte..."
              rows={3}
            />
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="category">Categoria *</Label>
              <ProductCategoryCombobox
                value={formData.category_id}
                onValueChange={(value) => setFormData({ ...formData, category_id: value })}
                required
              />
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Seleziona o digita per creare una nuova categoria
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="unit">Unità di Misura *</Label>
              <Select
                value={formData.unit}
                onValueChange={(value) => setFormData({ ...formData, unit: value })}
              >
                <SelectTrigger id="unit" className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {unitOptions.map((unit) => (
                    <SelectItem key={unit.value} value={unit.value}>
                      {unit.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="standard_cost">Costo Standard (€) *</Label>
              <Input
                id="standard_cost"
                type="number"
                step="0.01"
                min="0"
                value={formData.standard_cost}
                onChange={(e) =>
                  setFormData({ ...formData, standard_cost: parseFloat(e.target.value) || 0 })
                }
                required
                className="h-11"
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="product_type">Tipo Prodotto *</Label>
              <Select
                value={formData.product_type}
                onValueChange={(value: ProductType) => setFormData({ ...formData, product_type: value })}
              >
                <SelectTrigger id="product_type" className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="article">
                    <div className="flex flex-col">
                      <span className="font-medium">Articolo</span>
                      <span className="text-xs text-muted-foreground">Prodotto fisico singolo</span>
                    </div>
                  </SelectItem>
                  <SelectItem value="service">
                    <div className="flex flex-col">
                      <span className="font-medium">Servizio</span>
                      <span className="text-xs text-muted-foreground">Prestazione lavorativa</span>
                    </div>
                  </SelectItem>
                  <SelectItem value="composite">
                    <div className="flex flex-col">
                      <span className="font-medium">Composto</span>
                      <span className="text-xs text-muted-foreground">Prodotto con relazioni/componenti</span>
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                {formData.product_type === 'composite' &&
                  'Gestisci le relazioni nel tab "Relazioni" dopo aver salvato'}
              </p>
            </div>
          </div>

          <Separator />

          <div className="space-y-3">
            <div className="flex items-center gap-3 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-lg border border-slate-200 dark:border-slate-700">
              <input
                type="checkbox"
                id="is_active"
                checked={formData.is_active}
                onChange={(e) => setFormData({ ...formData, is_active: e.target.checked })}
                className="w-4 h-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
              />
              <Label htmlFor="is_active" className="text-sm cursor-pointer">
                Prodotto attivo e disponibile per l&#39;uso
              </Label>
            </div>

            <div className="flex items-center gap-3 p-4 bg-blue-50 dark:bg-blue-950/30 rounded-lg border border-blue-200 dark:border-blue-800">
              <input
                type="checkbox"
                id="is_package"
                checked={formData.is_package || false}
                onChange={(e) => setFormData({ ...formData, is_package: e.target.checked })}
                className="w-4 h-4 rounded border-blue-300 text-blue-600 focus:ring-blue-500"
              />
              <div className="flex-1">
                <Label htmlFor="is_package" className="text-sm font-medium cursor-pointer text-blue-900 dark:text-blue-100">
                  Questo è un contenitore/package (Box, Baule, Flight Case)
                </Label>
                <p className="text-xs text-blue-700 dark:text-blue-300 mt-1">
                  I package vengono tracciati per DDT e logistica ma NON appaiono nella lista materiali del preventivo
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 bg-purple-50 dark:bg-purple-950/30 rounded-lg border border-purple-200 dark:border-purple-800">
              <input
                type="checkbox"
                id="is_rentable"
                checked={formData.is_rentable || false}
                onChange={(e) => setFormData({ ...formData, is_rentable: e.target.checked })}
                className="w-4 h-4 rounded border-purple-300 text-purple-600 focus:ring-purple-500"
              />
              <div className="flex-1">
                <Label htmlFor="is_rentable" className="text-sm font-medium cursor-pointer text-purple-900 dark:text-purple-100">
                  Noleggiabile
                </Label>
                <p className="text-xs text-purple-700 dark:text-purple-300 mt-1">
                  Questo prodotto può essere noleggiato (vedi sezione &#34;Prezzi Noleggio&#34;)
                </p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Package Details - mostra solo se is_package è true */}
      {formData.is_package && (
        <Card className="border-blue-200 bg-blue-50/30">
          <CardHeader>
            <CardTitle className="text-blue-900">Dettagli Imballaggio</CardTitle>
            <CardDescription>Informazioni per calcolo pesi e volumi per i carichi</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="package_weight">Peso (kg)</Label>
                <Input
                  id="package_weight"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.package_weight || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, package_weight: parseFloat(e.target.value) || null })
                  }
                  placeholder="Es: 15.5"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="package_volume">Volume (m³)</Label>
                <Input
                  id="package_volume"
                  type="number"
                  step="0.001"
                  min="0"
                  value={formData.package_volume || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, package_volume: parseFloat(e.target.value) || null })
                  }
                  placeholder="Es: 0.5"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="package_dimensions">Dimensioni (LxWxH cm)</Label>
                <Input
                  id="package_dimensions"
                  value={formData.package_dimensions || ''}
                  onChange={(e) => setFormData({ ...formData, package_dimensions: e.target.value })}
                  placeholder="Es: 120x80x60"
                  className="h-11"
                />
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Codici e Tracciamento */}
      <Card>
        <CardHeader>
          <CardTitle>Codici e Tracciamento</CardTitle>
          <CardDescription>Barcode e QR code per tracciabilità</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="barcode">Barcode / EAN</Label>
              <div className="flex gap-2">
                <Input
                  id="barcode"
                  value={formData.barcode || ""}
                  onChange={(e) => setFormData({ ...formData, barcode: e.target.value })}
                  placeholder="8001234567890"
                  className="h-11 flex-1"
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  className="h-11 w-11 flex-shrink-0"
                  onClick={() => setScannerOpen(true)}
                  title="Scansiona barcode"
                >
                  <Scan className="h-5 w-5" />
                </Button>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="qr_code">QR Code</Label>
              <Input
                id="qr_code"
                value={formData.qr_code || ""}
                onChange={(e) => setFormData({ ...formData, qr_code: e.target.value })}
                placeholder="Codice QR personalizzato"
                className="h-11"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="location">Ubicazione Magazzino</Label>
            <Input
              id="location"
              value={formData.location || ""}
              onChange={(e) => setFormData({ ...formData, location: e.target.value })}
              placeholder="Es: Scaffale A3, Zona 2, Corsia B"
              className="h-11"
            />
          </div>
        </CardContent>
      </Card>

      {/* Gestione Scorte */}
      <Card>
        <CardHeader>
          <CardTitle>Gestione Scorte</CardTitle>
          <CardDescription>Livelli di riordino e tempi di consegna</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="default_supplier_id">Fornitore Predefinito</Label>
            <ComboboxSelect
              value={formData.default_supplier_id?.toString() || ""}
              onValueChange={(value) =>
                setFormData({ ...formData, default_supplier_id: value ? parseInt(value) : null })
              }
              onSearchChange={setSupplierSearch}
              options={suppliers.map(supplier => ({
                value: supplier.id!.toString(),
                label: supplier.company_name,
              }))}
              placeholder="Seleziona fornitore..."
              emptyText="Nessun fornitore trovato"
              loading={isLoadingSuppliers}
            />
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="reorder_level">Scorta Minima</Label>
              <Input
                id="reorder_level"
                type="number"
                step="0.01"
                min="0"
                value={formData.reorder_level}
                onChange={(e) =>
                  setFormData({ ...formData, reorder_level: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Livello di riordino automatico</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="reorder_quantity">Quantità Riordino</Label>
              <Input
                id="reorder_quantity"
                type="number"
                step="0.01"
                min="0"
                value={formData.reorder_quantity}
                onChange={(e) =>
                  setFormData({ ...formData, reorder_quantity: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Quantità da ordinare</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="lead_time_days">Tempo Consegna (giorni)</Label>
              <Input
                id="lead_time_days"
                type="number"
                min="0"
                value={formData.lead_time_days}
                onChange={(e) =>
                  setFormData({ ...formData, lead_time_days: parseInt(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Lead time del fornitore</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Prezzi Vendita */}
      <Card>
        <CardHeader>
          <CardTitle>Prezzi Vendita</CardTitle>
          <CardDescription>Prezzi di acquisto, margini e prezzi di vendita</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="purchase_price">Prezzo Acquisto (€)</Label>
              <Input
                id="purchase_price"
                type="number"
                step="0.01"
                min="0"
                value={formData.purchase_price || 0}
                onChange={(e) =>
                  setFormData({ ...formData, purchase_price: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Prezzo di acquisto dal fornitore</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="markup_percentage">Margine (%)</Label>
              <Input
                id="markup_percentage"
                type="number"
                step="0.01"
                min="0"
                value={formData.markup_percentage || 0}
                onChange={(e) => {
                  const markup = parseFloat(e.target.value) || 0;
                  const purchasePrice = formData.purchase_price || 0;
                  const salePrice = purchasePrice * (1 + markup / 100);
                  setFormData({
                    ...formData,
                    markup_percentage: markup,
                    sale_price: salePrice
                  });
                }}
                className="h-11"
              />
              <p className="text-xs text-slate-500">Margine applicato al prezzo acquisto</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="sale_price">Prezzo Vendita (€)</Label>
              <Input
                id="sale_price"
                type="number"
                step="0.01"
                min="0"
                value={formData.sale_price || 0}
                onChange={(e) =>
                  setFormData({ ...formData, sale_price: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Prezzo di vendita finale al cliente</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Prezzi Noleggio - mostra solo se is_rentable è true */}
      {formData.is_rentable && (
        <Card className="border-purple-200 bg-purple-50/30">
          <CardHeader>
            <CardTitle className="text-purple-900">Prezzi Noleggio</CardTitle>
            <CardDescription>Tariffe per il noleggio di questo producte</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="rental_price_daily">Tariffa Giornaliera (€/giorno)</Label>
                <Input
                  id="rental_price_daily"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.rental_price_daily || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, rental_price_daily: parseFloat(e.target.value) || 0 })
                  }
                  placeholder="Es: 50.00"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="rental_price_weekly">Tariffa Settimanale (€/settimana)</Label>
                <Input
                  id="rental_price_weekly"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.rental_price_weekly || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, rental_price_weekly: parseFloat(e.target.value) || 0 })
                  }
                  placeholder="Es: 300.00"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="rental_price_monthly">Tariffa Mensile (€/mese)</Label>
                <Input
                  id="rental_price_monthly"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.rental_price_monthly || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, rental_price_monthly: parseFloat(e.target.value) || 0 })
                  }
                  placeholder="Es: 1000.00"
                  className="h-11"
                />
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Note */}
      <Card>
        <CardHeader>
          <CardTitle>Note Aggiuntive</CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea
            value={formData.notes || ""}
            onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
            placeholder="Note interne, istruzioni di utilizzo, avvertenze..."
            rows={4}
          />
        </CardContent>
      </Card>

      {/* Form Actions */}
      <div className="flex items-center justify-end gap-4">
        <Button type="button" variant="outline" onClick={onCancel} disabled={isSubmitting}>
          Annulla
        </Button>
        <Button
          id="product-form-submit"
          type="submit"
          disabled={isSubmitting}
          className="shadow-md"
        >
          {isSubmitting ? (
            <>
              <div className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
              Salvataggio...
            </>
          ) : mode === 'create' ? (
            'Crea Prodotto'
          ) : (
            'Salva Modifiche'
          )}
        </Button>
      </div>

      {/* Barcode Scanner */}
      <BarcodeScanner
        open={scannerOpen}
        onOpenChange={setScannerOpen}
        onScan={(barcode) => {
          setFormData({ ...formData, barcode });
        }}
        title="Scansiona Barcode Prodotto"
        description="Scansiona il barcode del prodotto con la fotocamera"
      />
    </form>
  );
}
