'use client';

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { suppliersApi } from '@/lib/api/suppliers';
import { generateMaterialCode } from '@/lib/utils/code-generator';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { ComboboxSelect } from '@/components/combobox-select';
import {MaterialType} from "@/lib/types";

interface MaterialFormData {
  code?: string;
  name: string;
  description?: string;
  category: string;
  product_type?: MaterialType | undefined;
  unit: string;
  is_kit?: boolean;
  is_package?: boolean;
  package_weight?: number;
  package_volume?: number;
  package_dimensions?: string;
  is_rentable?: boolean;
  quantity_out_on_rental?: number;
  standard_cost: number;
  purchase_price?: number;
  markup_percentage?: number;
  sale_price?: number;
  rental_price_daily?: number;
  rental_price_weekly?: number;
  rental_price_monthly?: number;
  barcode?: string;
  qr_code?: string;
  default_supplier_id?: number | null;
  reorder_level: number;
  reorder_quantity: number;
  lead_time_days: number;
  location?: string;
  notes?: string;
  is_active: boolean;
}

interface MaterialFormProps {
  initialData?: Partial<MaterialFormData>;
  onSubmit: (data: MaterialFormData) => void;
  onCancel: () => void;
  isSubmitting?: boolean;
  mode: 'create' | 'edit';
}

const categoryOptions = [
  { value: 'construction', label: 'Edilizia' },
  { value: 'electrical', label: 'Elettrico' },
  { value: 'plumbing', label: 'Idraulica' },
  { value: 'tools', label: 'Attrezzi' },
  { value: 'equipment', label: 'Attrezzatura' },
  { value: 'general', label: 'Generale' },
];

const unitOptions = [
  { value: 'pz', label: 'Pezzi (pz)' },
  { value: 'kg', label: 'Kilogrammi (kg)' },
  { value: 'm', label: 'Metri (m)' },
  { value: 'm²', label: 'Metri quadri (m²)' },
  { value: 'm³', label: 'Metri cubi (m³)' },
  { value: 'l', label: 'Litri (l)' },
  { value: 'conf', label: 'Confezione (conf)' },
  { value: 'cad', label: 'Cadauno (cad)' },
];

export function MaterialForm({
  initialData,
  onSubmit,
  onCancel,
  isSubmitting = false,
  mode,
}: MaterialFormProps) {
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(mode === 'create' && !initialData?.code);
  const [formData, setFormData] = useState<MaterialFormData>({
    code: initialData?.code || '',
    name: initialData?.name || '',
    description: initialData?.description || '',
    category: initialData?.category || 'general',
    product_type: initialData?.product_type || 'physical',
    unit: initialData?.unit || 'pz',
    is_kit: initialData?.is_kit || false,
    is_package: initialData?.is_package || false,
    package_weight: initialData?.package_weight,
    package_volume: initialData?.package_volume,
    package_dimensions: initialData?.package_dimensions || '',
    is_rentable: initialData?.is_rentable || false,
    quantity_out_on_rental: initialData?.quantity_out_on_rental || 0,
    standard_cost: initialData?.standard_cost || 0,
    purchase_price: initialData?.purchase_price || 0,
    markup_percentage: initialData?.markup_percentage || 0,
    sale_price: initialData?.sale_price || 0,
    rental_price_daily: initialData?.rental_price_daily,
    rental_price_weekly: initialData?.rental_price_weekly,
    rental_price_monthly: initialData?.rental_price_monthly,
    barcode: initialData?.barcode || '',
    qr_code: initialData?.qr_code || '',
    default_supplier_id: initialData?.default_supplier_id || null,
    reorder_level: initialData?.reorder_level || 0,
    reorder_quantity: initialData?.reorder_quantity || 0,
    lead_time_days: initialData?.lead_time_days || 7,
    location: initialData?.location || '',
    notes: initialData?.notes || '',
    is_active: initialData?.is_active ?? true,
  });

  const [supplierSearch, setSupplierSearch] = useState('');

  // Lazy load suppliers only when searching
  const { data: suppliersData, isLoading: isLoadingSuppliers } = useQuery({
    queryKey: ['suppliers', { is_active: true, search: supplierSearch }],
    queryFn: () =>
      suppliersApi.getAll({
        is_active: true,
        search: supplierSearch,
        per_page: 50,
      }),
    enabled: !!supplierSearch || formData.default_supplier_id !== null,
  });

  const suppliers = suppliersData?.data ?? [];
  const selectedSupplier = suppliers.find((s: any) => s.id === formData.default_supplier_id);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Informazioni Generali */}
      <Card>
        <CardHeader>
          <CardTitle>Informazioni Generali</CardTitle>
          <CardDescription>Dati identificativi del materiale</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="code">
                Codice {mode === 'create' && '(opzionale - autogenerato)'}
              </Label>
              <Input
                id="code"
                value={formData.code}
                onChange={(e) => {
                  const newCode = e.target.value;
                  setFormData({ ...formData, code: newCode });
                  // If user manually edits code, disable auto-generation
                  if (mode === 'create') {
                    setIsCodeAutoGenerated(false);
                  }
                }}
                placeholder="MAT-001"
                className="h-11"
              />
              <p className="text-xs text-slate-500">
                {mode === 'create' && isCodeAutoGenerated
                  ? 'Si genera automaticamente dal nome'
                  : 'Se vuoto, verrà generato automaticamente'}
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="name" className="required">
                Nome Materiale *
              </Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => {
                  const newName = e.target.value;
                  setFormData({ ...formData, name: newName });

                  // Auto-generate code only in create mode and if not manually edited
                  if (mode === 'create' && isCodeAutoGenerated && newName) {
                    const generatedCode = generateMaterialCode(newName);
                    setFormData(prev => ({ ...prev, name: newName, code: generatedCode }));
                  }
                }}
                placeholder="Es: Cemento Portland CEM II/A-L 42,5 R"
                required
                className="h-11"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Descrizione</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Descrizione dettagliata del materiale..."
              rows={3}
            />
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="category">Categoria *</Label>
              <Select
                value={formData.category}
                onValueChange={(value) => setFormData({ ...formData, category: value })}
              >
                <SelectTrigger id="category" className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {categoryOptions.map((cat) => (
                    <SelectItem key={cat.value} value={cat.value}>
                      {cat.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="unit">Unità di Misura *</Label>
              <Select
                value={formData.unit}
                onValueChange={(value) => setFormData({ ...formData, unit: value })}
              >
                <SelectTrigger id="unit" className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {unitOptions.map((unit) => (
                    <SelectItem key={unit.value} value={unit.value}>
                      {unit.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="standard_cost">Costo Standard (€) *</Label>
              <Input
                id="standard_cost"
                type="number"
                step="0.01"
                min="0"
                value={formData.standard_cost}
                onChange={(e) =>
                  setFormData({ ...formData, standard_cost: parseFloat(e.target.value) || 0 })
                }
                required
                className="h-11"
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="product_type">Tipo Prodotto *</Label>
              <Select
                value={formData.product_type}
                onValueChange={(value: MaterialType) => setFormData({ ...formData, product_type: value })}
              >
                <SelectTrigger id="product_type" className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="physical">Bene (Vendita/Acquisto)</SelectItem>
                  <SelectItem value="service">Servizio</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <Separator />

          <div className="space-y-3">
            <div className="flex items-center gap-3 p-4 bg-slate-50 rounded-lg border border-slate-200">
              <input
                type="checkbox"
                id="is_active"
                checked={formData.is_active}
                onChange={(e) => setFormData({ ...formData, is_active: e.target.checked })}
                className="w-4 h-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
              />
              <Label htmlFor="is_active" className="text-sm cursor-pointer">
                Materiale attivo e disponibile per l&#39;uso
              </Label>
            </div>

            <div className="flex items-center gap-3 p-4 bg-green-50 rounded-lg border border-green-200">
              <input
                type="checkbox"
                id="is_kit"
                checked={formData.is_kit || false}
                onChange={(e) => setFormData({ ...formData, is_kit: e.target.checked })}
                className="w-4 h-4 rounded border-green-300 text-green-600 focus:ring-green-500"
              />
              <div className="flex-1">
                <Label htmlFor="is_kit" className="text-sm font-medium cursor-pointer text-green-900">
                  Questo è un kit (composto da altri materiali)
                </Label>
                <p className="text-xs text-green-700 mt-1">
                  I kit sono materiali composti da più componenti (vedi tab &#34;Componenti Kit&#34;)
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 bg-blue-50 rounded-lg border border-blue-200">
              <input
                type="checkbox"
                id="is_package"
                checked={formData.is_package || false}
                onChange={(e) => setFormData({ ...formData, is_package: e.target.checked })}
                className="w-4 h-4 rounded border-blue-300 text-blue-600 focus:ring-blue-500"
              />
              <div className="flex-1">
                <Label htmlFor="is_package" className="text-sm font-medium cursor-pointer text-blue-900">
                  Questo è un imballaggio/package (Box, Baule, Flight Case)
                </Label>
                <p className="text-xs text-blue-700 mt-1">
                  I package vengono tracciati per DDT e logistica ma NON appaiono nella lista materiali del preventivo
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 bg-purple-50 rounded-lg border border-purple-200">
              <input
                type="checkbox"
                id="is_rentable"
                checked={formData.is_rentable || false}
                onChange={(e) => setFormData({ ...formData, is_rentable: e.target.checked })}
                className="w-4 h-4 rounded border-purple-300 text-purple-600 focus:ring-purple-500"
              />
              <div className="flex-1">
                <Label htmlFor="is_rentable" className="text-sm font-medium cursor-pointer text-purple-900">
                  Noleggiabile
                </Label>
                <p className="text-xs text-purple-700 mt-1">
                  Questo materiale può essere noleggiato (vedi sezione &#34;Prezzi Noleggio&#34;)
                </p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Package Details - mostra solo se is_package è true */}
      {formData.is_package && (
        <Card className="border-blue-200 bg-blue-50/30">
          <CardHeader>
            <CardTitle className="text-blue-900">Dettagli Imballaggio</CardTitle>
            <CardDescription>Informazioni per calcolo pesi e volumi per i carichi</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="package_weight">Peso (kg)</Label>
                <Input
                  id="package_weight"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.package_weight || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, package_weight: parseFloat(e.target.value) || undefined })
                  }
                  placeholder="Es: 15.5"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="package_volume">Volume (m³)</Label>
                <Input
                  id="package_volume"
                  type="number"
                  step="0.001"
                  min="0"
                  value={formData.package_volume || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, package_volume: parseFloat(e.target.value) || undefined })
                  }
                  placeholder="Es: 0.5"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="package_dimensions">Dimensioni (LxWxH cm)</Label>
                <Input
                  id="package_dimensions"
                  value={formData.package_dimensions || ''}
                  onChange={(e) => setFormData({ ...formData, package_dimensions: e.target.value })}
                  placeholder="Es: 120x80x60"
                  className="h-11"
                />
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Codici e Tracciamento */}
      <Card>
        <CardHeader>
          <CardTitle>Codici e Tracciamento</CardTitle>
          <CardDescription>Barcode e QR code per tracciabilità</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="barcode">Barcode / EAN</Label>
              <Input
                id="barcode"
                value={formData.barcode}
                onChange={(e) => setFormData({ ...formData, barcode: e.target.value })}
                placeholder="8001234567890"
                className="h-11"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="qr_code">QR Code</Label>
              <Input
                id="qr_code"
                value={formData.qr_code}
                onChange={(e) => setFormData({ ...formData, qr_code: e.target.value })}
                placeholder="Codice QR personalizzato"
                className="h-11"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="location">Ubicazione Magazzino</Label>
            <Input
              id="location"
              value={formData.location}
              onChange={(e) => setFormData({ ...formData, location: e.target.value })}
              placeholder="Es: Scaffale A3, Zona 2, Corsia B"
              className="h-11"
            />
          </div>
        </CardContent>
      </Card>

      {/* Gestione Scorte */}
      <Card>
        <CardHeader>
          <CardTitle>Gestione Scorte</CardTitle>
          <CardDescription>Livelli di riordino e tempi di consegna</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="default_supplier_id">Fornitore Predefinito</Label>
            <ComboboxSelect
              value={formData.default_supplier_id?.toString() || undefined}
              onValueChange={(value) =>
                setFormData({ ...formData, default_supplier_id: value ? parseInt(value) : null })
              }
              onSearchChange={setSupplierSearch}
              options={suppliers.map((supplier: any) => ({
                value: supplier.id.toString(),
                label: supplier.company_name || supplier.name,
              }))}
              placeholder="Seleziona fornitore..."
              emptyText="Nessun fornitore trovato"
              loading={isLoadingSuppliers}
            />
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="reorder_level">Scorta Minima</Label>
              <Input
                id="reorder_level"
                type="number"
                step="0.01"
                min="0"
                value={formData.reorder_level}
                onChange={(e) =>
                  setFormData({ ...formData, reorder_level: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Livello di riordino automatico</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="reorder_quantity">Quantità Riordino</Label>
              <Input
                id="reorder_quantity"
                type="number"
                step="0.01"
                min="0"
                value={formData.reorder_quantity}
                onChange={(e) =>
                  setFormData({ ...formData, reorder_quantity: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Quantità da ordinare</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="lead_time_days">Tempo Consegna (giorni)</Label>
              <Input
                id="lead_time_days"
                type="number"
                min="0"
                value={formData.lead_time_days}
                onChange={(e) =>
                  setFormData({ ...formData, lead_time_days: parseInt(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Lead time del fornitore</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Prezzi Vendita */}
      <Card>
        <CardHeader>
          <CardTitle>Prezzi Vendita</CardTitle>
          <CardDescription>Prezzi di acquisto, margini e prezzi di vendita</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="purchase_price">Prezzo Acquisto (€)</Label>
              <Input
                id="purchase_price"
                type="number"
                step="0.01"
                min="0"
                value={formData.purchase_price || 0}
                onChange={(e) =>
                  setFormData({ ...formData, purchase_price: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Prezzo di acquisto dal fornitore</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="markup_percentage">Margine (%)</Label>
              <Input
                id="markup_percentage"
                type="number"
                step="0.01"
                min="0"
                value={formData.markup_percentage || 0}
                onChange={(e) => {
                  const markup = parseFloat(e.target.value) || 0;
                  const purchasePrice = formData.purchase_price || 0;
                  const salePrice = purchasePrice * (1 + markup / 100);
                  setFormData({
                    ...formData,
                    markup_percentage: markup,
                    sale_price: salePrice
                  });
                }}
                className="h-11"
              />
              <p className="text-xs text-slate-500">Margine applicato al prezzo acquisto</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="sale_price">Prezzo Vendita (€)</Label>
              <Input
                id="sale_price"
                type="number"
                step="0.01"
                min="0"
                value={formData.sale_price || 0}
                onChange={(e) =>
                  setFormData({ ...formData, sale_price: parseFloat(e.target.value) || 0 })
                }
                className="h-11"
              />
              <p className="text-xs text-slate-500">Prezzo di vendita finale al cliente</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Prezzi Noleggio - mostra solo se is_rentable è true */}
      {formData.is_rentable && (
        <Card className="border-purple-200 bg-purple-50/30">
          <CardHeader>
            <CardTitle className="text-purple-900">Prezzi Noleggio</CardTitle>
            <CardDescription>Tariffe per il noleggio di questo materiale</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="rental_price_daily">Tariffa Giornaliera (€/giorno)</Label>
                <Input
                  id="rental_price_daily"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.rental_price_daily || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, rental_price_daily: parseFloat(e.target.value) || undefined })
                  }
                  placeholder="Es: 50.00"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="rental_price_weekly">Tariffa Settimanale (€/settimana)</Label>
                <Input
                  id="rental_price_weekly"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.rental_price_weekly || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, rental_price_weekly: parseFloat(e.target.value) || undefined })
                  }
                  placeholder="Es: 300.00"
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="rental_price_monthly">Tariffa Mensile (€/mese)</Label>
                <Input
                  id="rental_price_monthly"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.rental_price_monthly || ''}
                  onChange={(e) =>
                    setFormData({ ...formData, rental_price_monthly: parseFloat(e.target.value) || undefined })
                  }
                  placeholder="Es: 1000.00"
                  className="h-11"
                />
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Note */}
      <Card>
        <CardHeader>
          <CardTitle>Note Aggiuntive</CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea
            value={formData.notes}
            onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
            placeholder="Note interne, istruzioni di utilizzo, avvertenze..."
            rows={4}
          />
        </CardContent>
      </Card>

      {/* Form Actions */}
      <div className="flex items-center justify-end gap-4">
        <Button type="button" variant="outline" onClick={onCancel} disabled={isSubmitting}>
          Annulla
        </Button>
        <Button type="submit" disabled={isSubmitting} className="shadow-md">
          {isSubmitting ? (
            <>
              <div className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
              Salvataggio...
            </>
          ) : mode === 'create' ? (
            'Crea Materiale'
          ) : (
            'Salva Modifiche'
          )}
        </Button>
      </div>
    </form>
  );
}
