<?php

namespace App\Events;

use App\Models\Ddt;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

/**
 * DdtCancelled Event
 *
 * Triggered when DDT status changes to Cancelled.
 *
 * CRITICAL: Must reverse all stock movements generated by this DDT.
 *
 * Listeners:
 * - ReverseStockMovementsListener (CRITICAL) - Reverses all stock movements and restores inventory
 * - NotifyWarehouseManagerListener - Sends notification
 * - LogDdtActivityListener - Audit trail
 */
class DdtCancelled
{
    use Dispatchable, SerializesModels;

    public function __construct(
        public readonly Ddt $ddt,
        public readonly string $reason,
        public readonly ?int $userId = null
    ) {}
}
