declare namespace App.Data {
export type ProductCategoryData = {
id: number | null;
code: string;
name: string;
description: string | null;
icon: string | null;
color: string | null;
sort_order: number;
is_active: boolean;
};
export type ProductComponentData = {
id?: number;
kit_product_id: number;
component_product_id: number;
quantity: number;
notes?: string | null;
created_at?: string;
updated_at?: string;
};
export type ProductData = {
id?: number;
code: string;
name: string;
description: string | null;
category: string;
product_type: App.Enums.ProductType;
unit: string;
standard_cost: number;
purchase_price: number;
markup_percentage: number;
sale_price: number;
rental_price_daily: number;
rental_price_weekly: number;
rental_price_monthly: number;
barcode: string | null;
qr_code: string | null;
default_supplier_id: number | null;
reorder_level: number;
reorder_quantity: number;
lead_time_days: number;
location: string | null;
notes: string | null;
is_rentable: boolean;
quantity_out_on_rental: number;
is_active: boolean;
is_package: boolean;
package_weight: number | null;
package_volume: number | null;
package_dimensions: string | null;
created_at?: string;
updated_at?: string;
deleted_at: string | null;
components?: any | Array<any>;
defaultSupplier?: App.Data.SupplierData | null;
calculated_sale_price: number;
composite_total_cost: number;
total_stock: number;
available_stock: number;
};
export type ProductRelationData = {
id: number | null;
product_id: number;
related_product_id: number;
relation_type_id: number;
quantity_type: App.Enums.ProductRelationQuantityType;
quantity_value: string;
is_visible_in_quote: boolean;
is_visible_in_material_list: boolean;
is_required_for_stock: boolean;
is_optional: boolean;
min_quantity_trigger: number | null;
max_quantity_trigger: number | null;
sort_order: number;
notes: string | null;
product?: App.Data.ProductData | null;
relatedProduct?: App.Data.ProductData | null;
relationType?: App.Data.ProductRelationTypeData | null;
};
export type ProductRelationTypeData = {
id: number | null;
code: string;
name: string;
description: string | null;
icon: string | null;
color: string | null;
sort_order: number;
is_active: boolean;
};
export type SupplierData = {
id?: number;
code: string;
company_name: string;
supplier_type: App.Enums.SupplierType;
personnel_type?: App.Enums.PersonnelType | null;
vat_number?: string | null;
tax_code?: string | null;
email?: string | null;
phone?: string | null;
mobile?: string | null;
website?: string | null;
address?: string | null;
city?: string | null;
province?: string | null;
postal_code?: string | null;
country?: string | null;
payment_terms?: string | null;
delivery_terms?: string | null;
discount_percentage?: number | null;
iban?: string | null;
bank_name?: string | null;
contact_person?: string | null;
contact_email?: string | null;
contact_phone?: string | null;
notes?: string | null;
specializations?: Array<any> | null;
is_active: boolean;
created_at?: string;
updated_at?: string;
deleted_at?: string | null;
};
export type UserData = {
id: number | null;
name: string;
email: string;
};
export type WarehouseData = {
id: number | null;
code: string;
name: string;
type: App.Enums.WarehouseType;
address: string | null;
city: string | null;
province: string | null;
postal_code: string | null;
manager_id: number | null;
notes: string | null;
is_active: boolean;
full_address: string | null;
total_value: number | null;
manager?: App.Data.UserData | null;
};
}
declare namespace App.Enums {
export type ContractType = 'permanent' | 'fixed_term' | 'seasonal' | 'project_based' | 'internship';
export type ContractorType = 'cooperative' | 'subcontractor' | 'temporary_agency';
export type DdtStatus = 'draft' | 'issued' | 'in_transit' | 'delivered' | 'cancelled';
export type DdtType = 'incoming' | 'outgoing' | 'internal' | 'rental_out' | 'rental_return' | 'return_from_customer' | 'return_to_supplier';
export type DependencyType = 'container' | 'accessory' | 'cable' | 'consumable' | 'tool';
export type LaborCostType = 'internal_labor' | 'subcontractor' | 'contractor';
export type MaterialRequestPriority = 'low' | 'medium' | 'high' | 'urgent';
export type MaterialRequestStatus = 'pending' | 'approved' | 'rejected' | 'delivered';
export type PayrollFrequency = 'monthly' | 'biweekly' | 'weekly';
export type PersonnelType = 'cooperative' | 'staffing_agency' | 'rental_with_operator' | 'subcontractor' | 'technical_services';
export type ProductRelationQuantityType = 'fixed' | 'multiplied' | 'formula';
export type ProductType = 'article' | 'service' | 'composite';
export type QuantityCalculationType = 'fixed' | 'ratio' | 'formula';
export type QuoteItemType = 'section' | 'item' | 'labor' | 'material';
export type RateContext = 'internal_cost' | 'customer_billing' | 'payroll';
export type RateType = 'hourly' | 'daily' | 'weekly' | 'monthly' | 'fixed_project';
export type ReturnReason = 'defective' | 'wrong_item' | 'excess' | 'warranty' | 'customer_dissatisfaction' | 'other';
export type SiteMaterialStatus = 'planned' | 'reserved' | 'delivered' | 'in_use' | 'completed' | 'returned';
export type SiteWorkerStatus = 'pending' | 'accepted' | 'rejected' | 'active' | 'completed' | 'cancelled';
export type StockMovementType = 'intake' | 'output' | 'transfer' | 'adjustment' | 'return' | 'waste' | 'rental_out' | 'rental_return' | 'site_allocation' | 'site_return';
export type SupplierType = 'materials' | 'personnel' | 'both';
export type WarehouseType = 'central' | 'site_storage' | 'mobile_truck';
export type WorkerType = 'employee' | 'freelancer' | 'external';
}
