<?php

namespace Database\Seeders;

use App\Models\Material;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class MaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get a supplier for default_supplier_id (optional)
        $supplier = Supplier::first();

        $materials = [
            // Materiali Edili - Construction Materials
            [
                'code' => 'MAT-001',
                'name' => 'Cemento Portland 42.5R',
                'description' => 'Cemento Portland tipo 42.5R in sacchi da 25kg',
                'category' => 'construction',
                'unit' => 'sacco',
                'standard_cost' => 8.50,
                'purchase_price' => 7.20,
                'sale_price' => 12.00,
                'markup_percentage' => 41.18,
                'product_type' => 'physical',
                'barcode' => '8001234567890',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 50,
                'reorder_quantity' => 200,
                'lead_time_days' => 3,
                'location' => 'A-01-01',
                'is_active' => true,
            ],
            [
                'code' => 'MAT-002',
                'name' => 'Sabbia fine lavata',
                'description' => 'Sabbia fine lavata per malte e intonaci',
                'category' => 'construction',
                'unit' => 'm³',
                'standard_cost' => 35.00,
                'purchase_price' => 30.00,
                'sale_price' => 50.00,
                'markup_percentage' => 42.86,
                'product_type' => 'physical',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 10,
                'reorder_quantity' => 30,
                'lead_time_days' => 2,
                'location' => 'ESTERNO-01',
                'is_active' => true,
            ],
            [
                'code' => 'MAT-003',
                'name' => 'Ghiaia 15-25mm',
                'description' => 'Ghiaia frantumata 15-25mm per calcestruzzo',
                'category' => 'construction',
                'unit' => 'm³',
                'standard_cost' => 40.00,
                'purchase_price' => 35.00,
                'sale_price' => 60.00,
                'markup_percentage' => 50.00,
                'product_type' => 'physical',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 10,
                'reorder_quantity' => 30,
                'lead_time_days' => 2,
                'location' => 'ESTERNO-02',
                'is_active' => true,
            ],
            [
                'code' => 'MAT-004',
                'name' => 'Mattoni pieni 25x12x5.5',
                'description' => 'Mattoni pieni in laterizio 25x12x5.5cm',
                'category' => 'construction',
                'unit' => 'pz',
                'standard_cost' => 0.45,
                'purchase_price' => 0.38,
                'sale_price' => 0.70,
                'markup_percentage' => 55.56,
                'product_type' => 'physical',
                'barcode' => '8001234567891',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 500,
                'reorder_quantity' => 2000,
                'lead_time_days' => 5,
                'location' => 'B-01-01',
                'is_active' => true,
            ],
            [
                'code' => 'MAT-005',
                'name' => 'Blocchi forati 30x20x19',
                'description' => 'Blocchi forati in laterizio per tramezzature',
                'category' => 'construction',
                'unit' => 'pz',
                'standard_cost' => 1.20,
                'purchase_price' => 1.00,
                'sale_price' => 1.80,
                'markup_percentage' => 50.00,
                'product_type' => 'physical',
                'barcode' => '8001234567892',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 300,
                'reorder_quantity' => 1000,
                'lead_time_days' => 5,
                'location' => 'B-01-02',
                'is_active' => true,
            ],

            // Materiali Elettrici - Electrical
            [
                'code' => 'ELET-001',
                'name' => 'Cavo elettrico 1.5mm²',
                'description' => 'Cavo unipolare N07V-K 1.5mm² - rotolo 100mt',
                'category' => 'electrical',
                'unit' => 'rotolo',
                'standard_cost' => 18.00,
                'purchase_price' => 15.00,
                'sale_price' => 28.00,
                'markup_percentage' => 55.56,
                'product_type' => 'physical',
                'barcode' => '8001234567893',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 20,
                'reorder_quantity' => 50,
                'lead_time_days' => 7,
                'location' => 'C-01-01',
                'is_active' => true,
            ],
            [
                'code' => 'ELET-002',
                'name' => 'Cavo elettrico 2.5mm²',
                'description' => 'Cavo unipolare N07V-K 2.5mm² - rotolo 100mt',
                'category' => 'electrical',
                'unit' => 'rotolo',
                'standard_cost' => 28.00,
                'purchase_price' => 24.00,
                'sale_price' => 42.00,
                'markup_percentage' => 50.00,
                'product_type' => 'physical',
                'barcode' => '8001234567894',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 20,
                'reorder_quantity' => 50,
                'lead_time_days' => 7,
                'location' => 'C-01-02',
                'is_active' => true,
            ],
            [
                'code' => 'ELET-003',
                'name' => 'Presa Bticino Living Light',
                'description' => 'Presa 2P+T 16A Bticino Living Light bianca',
                'category' => 'electrical',
                'unit' => 'pz',
                'standard_cost' => 3.50,
                'purchase_price' => 2.80,
                'sale_price' => 6.00,
                'markup_percentage' => 71.43,
                'product_type' => 'physical',
                'barcode' => '8001234567895',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 100,
                'reorder_quantity' => 300,
                'lead_time_days' => 5,
                'location' => 'C-02-01',
                'is_active' => true,
            ],
            [
                'code' => 'ELET-004',
                'name' => 'Interruttore Bticino Living Light',
                'description' => 'Interruttore 1P 16A Bticino Living Light bianco',
                'category' => 'electrical',
                'unit' => 'pz',
                'standard_cost' => 2.80,
                'purchase_price' => 2.20,
                'sale_price' => 5.00,
                'markup_percentage' => 78.57,
                'product_type' => 'physical',
                'barcode' => '8001234567896',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 100,
                'reorder_quantity' => 300,
                'lead_time_days' => 5,
                'location' => 'C-02-02',
                'is_active' => true,
            ],
            [
                'code' => 'ELET-005',
                'name' => 'Tubo corrugato Ø20mm',
                'description' => 'Tubo corrugato flessibile in PVC Ø20mm - rotolo 50mt',
                'category' => 'electrical',
                'unit' => 'rotolo',
                'standard_cost' => 12.00,
                'purchase_price' => 10.00,
                'sale_price' => 18.00,
                'markup_percentage' => 50.00,
                'product_type' => 'physical',
                'barcode' => '8001234567897',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 30,
                'reorder_quantity' => 100,
                'lead_time_days' => 3,
                'location' => 'C-03-01',
                'is_active' => true,
            ],

            // Idraulica - Plumbing
            [
                'code' => 'IDRA-001',
                'name' => 'Tubo multistrato Ø16mm',
                'description' => 'Tubo multistrato per acqua potabile Ø16mm - barra 4mt',
                'category' => 'plumbing',
                'unit' => 'barra',
                'standard_cost' => 8.50,
                'purchase_price' => 7.00,
                'sale_price' => 13.00,
                'markup_percentage' => 52.94,
                'product_type' => 'physical',
                'barcode' => '8001234567898',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 50,
                'reorder_quantity' => 200,
                'lead_time_days' => 5,
                'location' => 'D-01-01',
                'is_active' => true,
            ],
            [
                'code' => 'IDRA-002',
                'name' => 'Tubo multistrato Ø20mm',
                'description' => 'Tubo multistrato per acqua potabile Ø20mm - barra 4mt',
                'category' => 'plumbing',
                'unit' => 'barra',
                'standard_cost' => 11.50,
                'purchase_price' => 9.50,
                'sale_price' => 17.00,
                'markup_percentage' => 47.83,
                'product_type' => 'physical',
                'barcode' => '8001234567899',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 50,
                'reorder_quantity' => 200,
                'lead_time_days' => 5,
                'location' => 'D-01-02',
                'is_active' => true,
            ],
            [
                'code' => 'IDRA-003',
                'name' => 'Rubinetto lavabo cromato',
                'description' => 'Miscelatore monocomando per lavabo cromato',
                'category' => 'plumbing',
                'unit' => 'pz',
                'standard_cost' => 45.00,
                'purchase_price' => 38.00,
                'sale_price' => 75.00,
                'markup_percentage' => 66.67,
                'product_type' => 'physical',
                'barcode' => '8001234567900',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 10,
                'reorder_quantity' => 30,
                'lead_time_days' => 7,
                'location' => 'D-02-01',
                'is_active' => true,
            ],
            [
                'code' => 'IDRA-004',
                'name' => 'WC sospeso con seduta',
                'description' => 'Vaso WC sospeso in ceramica bianca con seduta',
                'category' => 'plumbing',
                'unit' => 'pz',
                'standard_cost' => 120.00,
                'purchase_price' => 100.00,
                'sale_price' => 180.00,
                'markup_percentage' => 50.00,
                'product_type' => 'physical',
                'barcode' => '8001234567901',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 5,
                'reorder_quantity' => 15,
                'lead_time_days' => 10,
                'location' => 'D-03-01',
                'is_active' => true,
            ],
            [
                'code' => 'IDRA-005',
                'name' => 'Lavabo 60cm con colonna',
                'description' => 'Lavabo in ceramica 60cm con colonna bianco',
                'category' => 'plumbing',
                'unit' => 'pz',
                'standard_cost' => 85.00,
                'purchase_price' => 70.00,
                'sale_price' => 130.00,
                'markup_percentage' => 52.94,
                'product_type' => 'physical',
                'barcode' => '8001234567902',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 5,
                'reorder_quantity' => 15,
                'lead_time_days' => 10,
                'location' => 'D-03-02',
                'is_active' => true,
            ],

            // Attrezzature - Equipment (rentable)
            [
                'code' => 'ATT-001',
                'name' => 'Betoniera 160L',
                'description' => 'Betoniera elettrica capacità 160 litri',
                'category' => 'equipment',
                'unit' => 'pz',
                'standard_cost' => 450.00,
                'purchase_price' => 380.00,
                'sale_price' => 680.00,
                'markup_percentage' => 51.11,
                'product_type' => 'physical',
                'is_rentable' => true,
                'barcode' => '8001234567903',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 2,
                'reorder_quantity' => 5,
                'lead_time_days' => 15,
                'location' => 'E-01-01',
                'is_active' => true,
            ],
            [
                'code' => 'ATT-002',
                'name' => 'Trapano a percussione',
                'description' => 'Trapano professionale a percussione 850W',
                'category' => 'tools',
                'unit' => 'pz',
                'standard_cost' => 120.00,
                'purchase_price' => 100.00,
                'sale_price' => 180.00,
                'markup_percentage' => 50.00,
                'product_type' => 'physical',
                'is_rentable' => true,
                'barcode' => '8001234567904',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 3,
                'reorder_quantity' => 10,
                'lead_time_days' => 7,
                'location' => 'E-02-01',
                'is_active' => true,
            ],
            [
                'code' => 'ATT-003',
                'name' => 'Ponteggio tubolare 3x3m',
                'description' => 'Modulo ponteggio tubolare 3x3 metri',
                'category' => 'equipment',
                'unit' => 'pz',
                'standard_cost' => 350.00,
                'purchase_price' => 300.00,
                'sale_price' => 520.00,
                'markup_percentage' => 48.57,
                'product_type' => 'physical',
                'is_rentable' => true,
                'barcode' => '8001234567905',
                'default_supplier_id' => $supplier?->id,
                'reorder_level' => 5,
                'reorder_quantity' => 20,
                'lead_time_days' => 20,
                'location' => 'ESTERNO-03',
                'is_active' => true,
            ],

            // Servizi - Services
            [
                'code' => 'SERV-001',
                'name' => 'Operaio generico',
                'description' => 'Manodopera operaio generico - tariffa oraria',
                'category' => 'labor',
                'unit' => 'ora',
                'standard_cost' => 18.00,
                'purchase_price' => 0.00,
                'sale_price' => 35.00,
                'markup_percentage' => 94.44,
                'product_type' => 'service',
                'is_active' => true,
            ],
            [
                'code' => 'SERV-002',
                'name' => 'Operaio specializzato',
                'description' => 'Manodopera operaio specializzato - tariffa oraria',
                'category' => 'labor',
                'unit' => 'ora',
                'standard_cost' => 25.00,
                'purchase_price' => 0.00,
                'sale_price' => 45.00,
                'markup_percentage' => 80.00,
                'product_type' => 'service',
                'is_active' => true,
            ],
            [
                'code' => 'SERV-003',
                'name' => 'Elettricista',
                'description' => 'Manodopera elettricista specializzato - tariffa oraria',
                'category' => 'labor',
                'unit' => 'ora',
                'standard_cost' => 30.00,
                'purchase_price' => 0.00,
                'sale_price' => 55.00,
                'markup_percentage' => 83.33,
                'product_type' => 'service',
                'is_active' => true,
            ],
            [
                'code' => 'SERV-004',
                'name' => 'Idraulico',
                'description' => 'Manodopera idraulico specializzato - tariffa oraria',
                'category' => 'labor',
                'unit' => 'ora',
                'standard_cost' => 30.00,
                'purchase_price' => 0.00,
                'sale_price' => 55.00,
                'markup_percentage' => 83.33,
                'product_type' => 'service',
                'is_active' => true,
            ],
        ];

        $created = 0;
        $skipped = 0;

        foreach ($materials as $materialData) {
            if (! Material::where('code', $materialData['code'])->exists()) {
                Material::create($materialData);
                $created++;
            } else {
                $skipped++;
            }
        }

        $this->command->info("Created {$created} materials, skipped {$skipped} existing materials.");
    }
}
