<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    public function __construct(
        private readonly string $companyName = '',
    ) {}

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $globalSettings = [
            // General
            [
                'key' => 'app.name',
                'value' => 'DGGM ERP',
                'type' => 'string',
                'group' => 'general',
                'is_public' => true,
                'description' => 'Application name displayed in the UI',
            ],
            [
                'key' => 'app.timezone',
                'value' => 'Europe/Rome',
                'type' => 'string',
                'group' => 'general',
                'is_public' => true,
                'description' => 'Default timezone for the application',
            ],
            [
                'key' => 'app.locale',
                'value' => 'it',
                'type' => 'string',
                'group' => 'general',
                'is_public' => true,
                'description' => 'Default locale for the application',
            ],

            // Company
            [
                'key' => 'company.name',
                'value' => $this->companyName !== '' ? $this->companyName : 'DGGM S.r.l.',
                'type' => 'string',
                'group' => 'company',
                'is_public' => false,
                'description' => 'Company legal name',
            ],
            [
                'key' => 'company.vat',
                'value' => 'IT12345678901',
                'type' => 'string',
                'group' => 'company',
                'is_public' => false,
                'description' => 'Company VAT number',
            ],
            [
                'key' => 'company.email',
                'value' => 'info@dggm.it',
                'type' => 'string',
                'group' => 'company',
                'is_public' => false,
                'description' => 'Company main email',
            ],
            [
                'key' => 'company.phone',
                'value' => '+39 0123 456789',
                'type' => 'string',
                'group' => 'company',
                'is_public' => false,
                'description' => 'Company main phone number',
            ],

            // Warehouse
            [
                'key' => 'warehouse.low_stock_threshold',
                'value' => '10',
                'type' => 'number',
                'group' => 'warehouse',
                'is_public' => false,
                'description' => 'Default threshold for low stock alerts',
            ],
            [
                'key' => 'warehouse.enable_notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'warehouse',
                'is_public' => false,
                'description' => 'Enable warehouse notifications',
            ],
            [
                'key' => 'warehouse.ddt_code_prefix',
                'value' => 'DDT',
                'type' => 'string',
                'group' => 'warehouse',
                'is_public' => false,
                'description' => 'Prefix for DDT (transport document) codes (e.g., DDT-2026-0001)',
            ],
            [
                'key' => 'warehouse.ddt_code_format',
                'value' => '{prefix}-{year}-{number:4}',
                'type' => 'string',
                'group' => 'warehouse',
                'is_public' => false,
                'description' => 'Format for DDT codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],
            [
                'key' => 'warehouse.movement_code_prefix',
                'value' => 'MOV',
                'type' => 'string',
                'group' => 'warehouse',
                'is_public' => false,
                'description' => 'Prefix for stock movement codes (e.g., MOV-20260211-001)',
            ],
            [
                'key' => 'warehouse.movement_code_format',
                'value' => '{prefix}-{date}-{number:3}',
                'type' => 'string',
                'group' => 'warehouse',
                'is_public' => false,
                'description' => 'Format for stock movement codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],

            // Email
            [
                'key' => 'email.enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'email',
                'is_public' => false,
                'description' => 'Enable email sending',
            ],
            [
                'key' => 'email.from_address',
                'value' => 'noreply@dggm.it',
                'type' => 'string',
                'group' => 'email',
                'is_public' => false,
                'description' => 'Default from email address',
            ],

            // Notifications
            [
                'key' => 'notifications.channels',
                'value' => json_encode(['database', 'mail']),
                'type' => 'json',
                'group' => 'notifications',
                'is_public' => false,
                'description' => 'Enabled notification channels',
            ],

            // Features (Feature Flags)
            [
                'key' => 'features.enable_gps_tracking',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'is_public' => false,
                'is_feature_flag' => true,
                'description' => 'Enable GPS tracking for time entries',
                'order' => 10,
            ],
            [
                'key' => 'features.enable_material_requests',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'is_public' => false,
                'is_feature_flag' => true,
                'description' => 'Enable material request system',
                'order' => 20,
            ],
            [
                'key' => 'features.enable_semantic_search',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'is_public' => false,
                'is_feature_flag' => true,
                'description' => 'Enable AI-powered semantic search for products',
                'order' => 30,
            ],
            [
                'key' => 'features.enable_pdf_generation',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'is_public' => false,
                'is_feature_flag' => true,
                'description' => 'Enable PDF generation for quotes and invoices',
                'order' => 40,
            ],
            [
                'key' => 'features.enable_notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'is_public' => false,
                'is_feature_flag' => true,
                'description' => 'Enable system notifications',
                'order' => 50,
            ],

            // Pricing & Rental
            [
                'key' => 'pricing.default_vat_rate',
                'value' => '22',
                'type' => 'number',
                'group' => 'pricing',
                'is_public' => true,
                'description' => 'Aliquota IVA predefinita in percentuale',
            ],
            [
                'key' => 'pricing.default_markup_percent',
                'value' => '30',
                'type' => 'number',
                'group' => 'pricing',
                'is_public' => false,
                'description' => 'Default markup percentage for products',
                'min_value' => 0,
                'max_value' => 1000,
            ],
            [
                'key' => 'rental.daily_rate_percent',
                'value' => '15',
                'type' => 'number',
                'group' => 'pricing',
                'is_public' => false,
                'description' => 'Daily rental divisor: sale_price / 15 = daily_rate',
                'min_value' => 0,
                'max_value' => 100,
            ],
            [
                'key' => 'rental.hours_per_day',
                'value' => '8',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Divisore per calcolo prezzo orario (prezzo_giornaliero / ore_giorno)',
                'min_value' => '1',
                'max_value' => '24',
            ],
            [
                'key' => 'pricing.purchase_price_strategy',
                'value' => 'highest',
                'type' => 'string',
                'group' => 'pricing',
                'is_public' => false,
                'description' => 'How to calculate purchase price from multiple suppliers (highest, lowest, weighted_average)',
            ],
            [
                'key' => 'pricing.auto_update_on_purchase',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'pricing',
                'is_public' => false,
                'description' => 'Automatically update product prices when receiving stock',
            ],
            [
                'key' => 'pricing.update_only_if_higher',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'pricing',
                'is_public' => false,
                'description' => 'Update prices only if new purchase price is higher (keep temporary discounts)',
            ],
            [
                'key' => 'pricing.auto_recalculate_price_list_on_purchase',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'pricing',
                'is_public' => false,
                'description' => 'Se abilitato, ricalcola automaticamente i prezzi di vendita e noleggio nei listini quando viene aggiornato il costo di acquisto (al carico di magazzino o DDT). Disabilitato di default.',
                'order' => 99,
            ],
            [
                'key' => 'rental.exponent_curve',
                'value' => '0.69',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Rental power-decay curve exponent (default 0.69). Aumentare per sconto durata più aggressivo.',
                'min_value' => 0.3,
                'max_value' => 1.0,
            ],
            [
                'key' => 'rental.decay_strength',
                'value' => '0.27',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Forza del decadimento logaritmico (default 0.27). 0 = nessun decadimento (pura potenza).',
                'min_value' => 0.0,
                'max_value' => 0.9,
            ],
            [
                'key' => 'rental.max_duration_reference',
                'value' => '30',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Riferimento giorni per normalizzare il decadimento (default 30 = mensile).',
                'min_value' => 7,
                'max_value' => 365,
            ],
            [
                'key' => 'rental.duration_offset',
                'value' => '0.15',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Offset additivo al moltiplicatore (default 0.15). Garantisce Mult(1)=1.15 eccetto caso speciale.',
                'min_value' => 0.0,
                'max_value' => 1.0,
            ],
            [
                'key' => 'rental.max_period_cap_days',
                'value' => '90',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Soglia stagionale giorni: floor del moltiplicatore per noleggi > N giorni (default 90).',
                'min_value' => 30,
                'max_value' => 365,
            ],
            [
                'key' => 'rental.commercial_index',
                'value' => '1.00',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Indice commerciale globale. Moltiplicatore su tutti i prezzi noleggio (es: 1.10 = +10% di mercato).',
                'min_value' => '0.50',
                'max_value' => '3.00',
            ],

            // Rental — parametri economici
            [
                'key' => 'rental.break_even_days',
                'value' => '40',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Giorni noleggio per ammortizzare il costo di acquisto',
                'min_value' => 1,
                'max_value' => 365,
            ],
            [
                'key' => 'rental.margin_percentage',
                'value' => '20',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Margine % sul BaseDay calcolato',
                'min_value' => 0,
                'max_value' => 100,
            ],

            // Rental — scarcity & premium
            [
                'key' => 'rental.scarcity_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Abilita scarcity pricing globale',
            ],
            [
                'key' => 'rental.scarcity_threshold',
                'value' => '0.30',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Ratio disponibilità sotto cui si applica scarcity',
                'min_value' => 0.0,
                'max_value' => 1.0,
            ],
            [
                'key' => 'rental.scarcity_multiplier',
                'value' => '1.10',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Moltiplicatore scarcity (+10%)',
                'min_value' => 1.0,
                'max_value' => 3.0,
            ],
            [
                'key' => 'rental.premium_multiplier',
                'value' => '1.15',
                'type' => 'number',
                'group' => 'rental',
                'is_public' => false,
                'description' => 'Moltiplicatore prodotti premium (+15%)',
                'min_value' => 1.0,
                'max_value' => 3.0,
            ],

            // Subrental
            [
                'key' => 'subrental.markup_default',
                'value' => '0.30',
                'type' => 'number',
                'group' => 'subrental',
                'is_public' => false,
                'description' => 'Markup default su costo fornitore sub-noleggio',
                'min_value' => 0.0,
                'max_value' => 10.0,
            ],
            [
                'key' => 'subrental.pricing_mode',
                'value' => 'flexible_with_alert',
                'type' => 'string',
                'group' => 'subrental',
                'is_public' => false,
                'description' => 'Modalità pricing sub-noleggio: block o flexible_with_alert',
            ],
            [
                'key' => 'subrental.min_margin_percent',
                'value' => '15',
                'type' => 'number',
                'group' => 'subrental',
                'is_public' => false,
                'description' => 'Soglia margine % per alert',
                'min_value' => 0,
                'max_value' => 100,
            ],
            [
                'key' => 'subrental.auto_supplier_selection',
                'value' => 'auto',
                'type' => 'string',
                'group' => 'subrental',
                'is_public' => false,
                'description' => 'Modalità selezione fornitore sub-noleggio: auto o manual',
            ],
            [
                'key' => 'subrental.price_weight',
                'value' => '0.60',
                'type' => 'number',
                'group' => 'subrental',
                'is_public' => false,
                'description' => 'Peso prezzo nel calcolo score fornitore',
                'min_value' => 0.0,
                'max_value' => 1.0,
            ],
            [
                'key' => 'subrental.reliability_weight',
                'value' => '0.40',
                'type' => 'number',
                'group' => 'subrental',
                'is_public' => false,
                'description' => 'Peso reliability nel calcolo score fornitore',
                'min_value' => 0.0,
                'max_value' => 1.0,
            ],

            // Products — code generation
            [
                'key' => 'products.code_prefix',
                'value' => 'PRD',
                'type' => 'string',
                'group' => 'products',
                'is_public' => false,
                'description' => 'Prefix for product codes (e.g., PRD-00001)',
            ],
            [
                'key' => 'products.code_format',
                'value' => '{prefix}-{number:5}',
                'type' => 'string',
                'group' => 'products',
                'is_public' => false,
                'description' => 'Format for product codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],

            // Sites — code generation
            [
                'key' => 'sites.code_prefix',
                'value' => 'CANT',
                'type' => 'string',
                'group' => 'sites',
                'is_public' => false,
                'description' => 'Prefix for construction site codes (e.g., CANT-0001)',
            ],
            [
                'key' => 'sites.code_format',
                'value' => '{prefix}-{number:4}',
                'type' => 'string',
                'group' => 'sites',
                'is_public' => false,
                'description' => 'Format for site codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],

            // Codes — registry entities
            [
                'key' => 'codes.worker_prefix',
                'value' => 'LAV',
                'type' => 'string',
                'group' => 'codes',
                'is_public' => false,
                'description' => 'Prefix for worker codes (e.g., LAV-00001)',
            ],
            [
                'key' => 'codes.worker_format',
                'value' => '{prefix}-{number:5}',
                'type' => 'string',
                'group' => 'codes',
                'is_public' => false,
                'description' => 'Format for worker codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],
            [
                'key' => 'codes.supplier_prefix',
                'value' => 'FOR',
                'type' => 'string',
                'group' => 'codes',
                'is_public' => false,
                'description' => 'Prefix for supplier codes (e.g., FOR-00001)',
            ],
            [
                'key' => 'codes.supplier_format',
                'value' => '{prefix}-{number:5}',
                'type' => 'string',
                'group' => 'codes',
                'is_public' => false,
                'description' => 'Format for supplier codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],
            [
                'key' => 'codes.contractor_prefix',
                'value' => 'CON',
                'type' => 'string',
                'group' => 'codes',
                'is_public' => false,
                'description' => 'Prefix for contractor codes (e.g., CON-00001)',
            ],
            [
                'key' => 'codes.contractor_format',
                'value' => '{prefix}-{number:5}',
                'type' => 'string',
                'group' => 'codes',
                'is_public' => false,
                'description' => 'Format for contractor codes. Available placeholders: {prefix}, {year}, {date}, {number:X}',
            ],

            // Theme / UI (Public settings for dynamic UI)
            [
                'key' => 'theme.primary_color',
                'value' => '#0e172b',
                'type' => 'color',
                'group' => 'theme',
                'is_public' => true,
                'description' => 'Primary brand color',
            ],
            [
                'key' => 'theme.secondary_color',
                'value' => '#f5f5f5',
                'type' => 'color',
                'group' => 'theme',
                'is_public' => true,
                'description' => 'Secondary brand color',
            ],
            [
                'key' => 'theme.logo_url',
                'value' => null,
                'type' => 'string',
                'group' => 'theme',
                'is_public' => true,
                'description' => 'Company logo URL (upload via settings)',
            ],
            [
                'key' => 'theme.favicon_url',
                'value' => null,
                'type' => 'string',
                'group' => 'theme',
                'is_public' => true,
                'description' => 'Favicon URL (upload via settings)',
            ],
            [
                'key' => 'ui.items_per_page',
                'value' => '15',
                'type' => 'number',
                'group' => 'ui',
                'is_public' => true,
                'description' => 'Default items per page in tables',
            ],
            [
                'key' => 'ui.date_format',
                'value' => 'DD/MM/YYYY',
                'type' => 'string',
                'group' => 'ui',
                'is_public' => true,
                'description' => 'Date format for UI display',
            ],
        ];

        foreach ($globalSettings as $setting) {
            Setting::firstOrCreate(
                ['key' => $setting['key'], 'user_id' => null],
                $setting
            );
        }
    }
}
